vltpkg/vltpkg

- infra/build/test/bundle.ts
- pnpm-lock.yaml
- src/gui/package.json
- src/gui/src/components/dashboard-grid/index.tsx
- src/gui/src/components/explorer-grid/selected-item.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/src/components/ui/shiki.tsx
- src/gui/src/components/ui/tabs.tsx
- src/gui/src/components/ui/theme-provider.tsx
- src/gui/src/state/index.ts
- src/gui/src/state/types.ts
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/selected-item.tsx.snap
- src/gui/test/components/explorer-grid/selected-item.tsx
Adds a tab navigation to the selected item view of the explorer, in which it renders the contents of the manifest using https://shiki.style
> gui: add package.json rendered tab

- src/graph/src/graph.ts
- src/graph/src/ideal/add-nodes.ts
- src/graph/src/ideal/append-nodes.ts
- src/graph/src/ideal/build-ideal-from-starting-graph.ts
- src/graph/src/ideal/get-importer-specs.ts
- src/graph/src/lockfile/load.ts
- src/graph/tap-snapshots/test/graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/append-nodes.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/build-ideal-from-starting-graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/build.ts.test.cjs
- src/graph/tap-snapshots/test/lockfile/load.ts.test.cjs
- src/graph/tap-snapshots/test/reify/optional-fail.ts.test.cjs
- src/graph/test/ideal/append-nodes.ts
- src/graph/test/ideal/build-ideal-from-starting-graph.ts
- src/graph/test/ideal/build.ts
- src/graph/test/lockfile/load.ts
- src/registry-client/src/index.ts
- src/registry-client/test/index.ts
- src/vlt/src/config/definition.ts
- src/vlt/src/config/index.ts
- src/vlt/tap-snapshots/test/commands/help.ts.test.cjs
- src/vlt/tap-snapshots/test/config/definition.ts.test.cjs
This fixes an issue where we'd crash when the network is flaky, with `ECONNREFUSED`, `ECONNRESET`, `EPIPE`, and `UND_ERR_SOCKET`.
Using undici's `RetryHandler` takes care of this transparently, including retrying `GET` requests with a `Range` header (for servers that advertise support for it) if the body had already been partly consumed.
> registry-client: retry on transient network fails

- src/graph/src/graph.ts
- src/graph/src/ideal/add-nodes.ts
- src/graph/src/ideal/append-nodes.ts
- src/graph/src/ideal/build-ideal-from-starting-graph.ts
- src/graph/src/ideal/get-importer-specs.ts
- src/graph/src/lockfile/load.ts
- src/graph/tap-snapshots/test/graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/append-nodes.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/build-ideal-from-starting-graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/build.ts.test.cjs
- src/graph/tap-snapshots/test/lockfile/load.ts.test.cjs
- src/graph/tap-snapshots/test/reify/optional-fail.ts.test.cjs
- src/graph/test/ideal/append-nodes.ts
- src/graph/test/ideal/build-ideal-from-starting-graph.ts
- src/graph/test/ideal/build.ts
- src/graph/test/lockfile/load.ts
This PR fixes adding nameless dependency specs when using the cli
e.g: `vlt install github:foo/bar` along with fixing inconsistencies
when merging cli-defined dependencies with manifest-defined values.
A few connected changes found when turning many stones related to this
problem that are worthy of mention:
- `Graph.removeNode` removes the edge from its `from` node instead of
just unsetting the `to` value of that edge.
- `append-nodes` will fix up and update entries in the user-provided
`add` values, so that we can add a proper dependency name when writing
to that importer `package.json` at the end of reify.
- cleaned up the logic between `ideal.build` and its
`get-importer-specs` module so values should be properly merged when
adding / removing new dependencies.
- Make lockfile load a …
> graph: fix adding nameless specs 

- src/vlt/src/config/index.ts
- src/vlt/test/config/index.ts
- fixes root resolution which was causing errors to occur when trying to run `vlt` inside a nested dir of any git project
- the root-cause was incorrectly treating the existence of `.git` as both a backstop & a root identifier
- this change also... 
- resolves issues where a previously found/known-good root existed while walking up the path but was ignored
- treats the cwd as the preferred default root instead of the `.git` backstop (which is less confusing for end-users if no known root is found while walking up the path)
- the existence of `vlt-workspaces.json` continues to be treated as both a backstop & a well-known root location
- since I'm not opening a separate issue for the resolution error/backstop, here's a minimum reproduction to see the issue with the previous algorithm …
> fix: project root resolution

- src/gui/src/components/explorer-grid/add-dependencies-popover.tsx
- src/gui/src/components/explorer-grid/dependency-side-bar.tsx
- src/gui/src/components/explorer-grid/index.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/test/components/explorer-grid/__snapshots__/add-dependencies-popover.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
- src/gui/test/components/explorer-grid/add-dependencies-popover.tsx
- src/gui/test/components/explorer-grid/side-item.tsx
- src/vlt/src/start-gui.ts
- src/vlt/src/uninstall.ts
- src/vlt/tap-snapshots/test/uninstall.ts.test.cjs
- src/vlt/test/install.ts
- src/vlt/test/start-gui.ts
- src/vlt/test/uninstall.ts
- Added a simplistic drop down to direct dependencies of importer nodes that appear on the dependency side bar, providing an UI that is similar to pining projects on dashboard in order to display an option to remove these installed packages.
- Refactored the backend integration to have both `install` and `uninstall` share the same backend integration.
- Corrected nested use of buttons in the `AddDependenciesPopover` component.
https://github.com/user-attachments/assets/cf8a4f03-5d9c-499f-9ab3-3bf4e7bcbe01
Fixes: #244
Fixes: #243 
Fixes: #242
> Add UI to remove dependencies

- src/error-cause/src/index.ts
- src/error-cause/test/index.ts
- src/git/src/which.ts
- src/package-info/src/index.ts
- src/package-json/src/index.ts
- src/query/src/pseudo.ts
- src/registry-client/src/index.ts
- src/spec/src/browser.ts
- src/tar/src/pool.ts
- src/vlt/src/config/index.ts
- src/vlt/src/exec-command.ts
- src/vlt/src/index.ts
- src/vlt/src/output.ts
- src/workspaces/src/index.ts
We turned on `useUnknownInCatchVariables` in our tsconfig when we started linting 9cc25431b5567aa5c094c4557b7626df75a74d41. So I think it makes sense for the `cause` property on `ErrorCauseObject` to be `unknown` as well. This removes the need down to do `{ cause: er as Error }` every time we want to throw a previously caught error.
I originally set the `cause: ErrorCause` argument for all the exported `error|typeError|syntaxError()` functions to also be `unknown` but this gets rid of some of the type safety. So you still have to pass an actual `Error | ErrorCauseObject` to the functions, but the cause object can now have `{ cause: unknown }`.
This also adds some type guard utility functions to `error-cause` which I used to clean up some `er instanceof Error` checks.
> error-cause: allow cause to be unknown

- src/vlt/src/commands/uninstall.ts
- src/vlt/tap-snapshots/test/commands/uninstall.ts.test.cjs
- src/vlt/test/commands/uninstall.ts
Following up from 08488add800b3db1488cf5f0910406d9c0384edd the uninstall command should now reuse `src/uninstall.ts`.
> vlt: refactor uninstall command

- src/graph/src/reify/update-importers-package-json.ts
- src/graph/tap-snapshots/test/reify/update-importers-package-json.ts.test.cjs
- src/graph/test/reify/update-importers-package-json.ts
If the user provides a specific range in order to add a package using `vlt install` then we should preserve that used prefix when saving to the `package.json` file.
e.g (installing a package named `foo`, assuming a dist-tag of `latest` pointing to version `1.1.2`):
`vlt install foo` -> `"foo": "^1.1.2"`
`vlt install foo@latest` -> `"foo": "^1.1.2"`
`vlt install foo@1.1.2` -> `"foo": "1.1.2"`
`vlt install foo@1 || 2` -> `"foo": "1 || 2"`
`vlt install foo@~1.1.0` -> `"foo": "~1.1.0"`
Relates to: https://github.com/vltpkg/vltpkg/issues/266
> graph: store user-defined prefix

- src/graph/src/lockfile/load-nodes.ts
- src/graph/src/reify/add-nodes.ts
- src/graph/src/types.ts
- src/graph/tap-snapshots/test/ideal/build-ideal-from-starting-graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/build.ts.test.cjs
- src/graph/tap-snapshots/test/lockfile/load-nodes.ts.test.cjs
- src/graph/tap-snapshots/test/lockfile/load.ts.test.cjs
- src/gui/src/state/load-graph.ts
- src/gui/test/state/__snapshots__/load-graph.ts.snap
- src/package-info/src/index.ts
- src/package-info/test/index.ts
- src/query/test/fixtures/graph.ts
Tweaked **package-info** to make it possible for it to accept `resolved` & `integrity` values and ensures that **graph** now properly sends these values whenever available. Also fixes lockfile load to make sure that `resolved` values for default registry gets properly inferred and added to nodes.
```
$ hyperfine --warmup 2 --prepare="rm -rf node_modules" --setup="rm -rf $HOME/Library/Caches/vlt" -r=16 --cleanup="sleep 1" "vlt install" "vlt-main install"
Benchmark 1: vlt install
Time (mean ± σ):      1.910 s ±  0.042 s    [User: 3.209 s, System: 2.273 s]
Range (min … max):    1.820 s …  1.982 s    16 runs
Benchmark 2: vlt-main install
Time (mean ± σ):      2.443 s ±  0.046 s    [User: 3.905 s, System: 2.396 s]
Range (min … max):    2.380 s …  2.530 s    16 runs
Summary
vlt install ran
1.28 …
```
> Reify should use lockfile`resolved` & `integrity` values

- src/cache/src/index.ts
Increasing the in-memory cache size improves performance when installing average-sized projects from a cold cache, since reify loads information from disk rather than the in-memory cache once items start to be evicted from our LRU cache.
Bumping its value by 10x helps average size install but also particularly really large ones.
```
$ hyperfine --warmup=1 --prepare="rm -rf node_modules; rm -rf $HOME/Library/Caches/vlt || true" -r=4 --cleanup="sleep 1" "vlt install" "vlt-main install"
Benchmark 1: vlt install
Time (mean ± σ):     17.275 s ± 12.380 s    [User: 7.584 s, System: 4.426 s]
Range (min … max):    6.039 s … 28.580 s    4 runs
Benchmark 2: vlt-main install
Time (mean ± σ):     19.276 s ± 12.882 s    [User: 7.916 s, System: 4.791 s]
Range (min … max):    6.488 s … 31.055 s    4 runs …
```
> cache: increase in-memory cache size

- src/registry-client/src/cache-entry.ts
Added a few instances that were missing memoizing the `isJSON` and `json` values.
> registry-client: add missing json memoization

- src/vlt/src/config/definition.ts
- src/vlt/src/ignored-homedir-folder-names.ts
- src/vlt/src/read-project-folders.ts
- src/vlt/src/start-gui.ts
- src/vlt/tap-snapshots/test/commands/help.ts.test.cjs
- src/vlt/tap-snapshots/test/config/definition.ts.test.cjs
- src/vlt/test/read-project-folders.ts
- src/vlt/test/start-gui.ts
This changeset introduces a new system for finding out projects to be displayed in the GUI dashboard.
It's now configurable via a `dashboard-root` config option and otherwise defaults to reading all projects available starting from the user home directory.
Fixes: https://github.com/vltpkg/vltpkg/issues/271
> vlt: add new dashboard root path logic

- src/vlt/src/start-gui.ts
- src/vlt/test/start-gui.ts
If the current working directory is recognized as being inside a project then the default starting route should be explore, otherwise it should default to opening the dashboard route.
Fixes: https://github.com/vltpkg/vltpkg/issues/262
> vlt: `vlt gui` should open explore if project found

- src/gui/src/components/explorer-grid/dependency-side-bar.tsx
- src/gui/src/components/explorer-grid/save-query.tsx
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/save-query.tsx.snap
React development mode was complaining about nested buttons, setting `asChild` props fixes the warnings.
> gui: fix react render warnings

- src/gui/src/components/explorer-grid/dependency-side-bar.tsx
- src/gui/src/components/explorer-grid/selected-item.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/src/components/explorer-grid/types.ts
- src/gui/src/state/index.ts
- src/gui/src/state/types.ts
- src/gui/test/components/explorer-grid/__snapshots__/dependency-side-bar.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/selected-item.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
Rewrites a good part of the logic drawing connection lines between a selected items and its dependencies. The new system now dynamically retrieves the top-most value and calculate the height of each connection line based on that.
> gui: fix explorer connecting line issues

- src/graph/src/browser.ts
- src/gui/src/components/explorer-grid/dependency-side-bar.tsx
- src/gui/src/components/explorer-grid/index.tsx
- src/gui/test/components/explorer-grid/__snapshots__/dependency-side-bar.tsx.snap
- src/gui/test/components/explorer-grid/dependency-side-bar.tsx
Now the GUI Explorer also display uninstalled dependencies for a given selected item.
> gui: add uninstalled dependencies

- src/vlt/src/exec-command.ts
When running `vlt exec` in a given project (with no workspaces involved) the cli fails to forward the exit error code.
This changeset fixes that by properly forwarding the exit error code in the "single target" (or no workspaces) branch of logic.
Fixes: https://github.com/vltpkg/vltpkg/issues/157
> vlt: fix exec exit code for single target

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- eslint.config.mjs
- infra/build/src/bin/benchmark.ts
- infra/build/src/bin/publish.ts
- infra/build/src/matrix.ts
- infra/build/src/placeholder-bin.js
- infra/build/src/postinstall.js
- infra/build/test/matrix.ts
This adds a separate step to the `publish.yml` workflow that will publish the Deno compiled binary to `vlt@compiled`.
It also publishes the 5 platform/arch combinations supported by Deno to `@vltpkg/cli-{PLATFORM}-{ARCH}` which are set as optional dependencies with the correct picked by a postinstall script.
Currently if a correct optional dep is not found there is a placeholder bin that will just error with a message saying it's probably because `--ignore-scripts` or `--no-optional` was used and to try again. This is a tradeoff for now because I'd rather this special `compiled` tag not fallback to running the bundled JS version so we can ensure the compiled version is always being run for perf testing.
Also the `compiled` tag currently only contains the main `vlt` bin and not any of the …
> publish: compiled binaries to a separate tag

- eslint.config.mjs
- infra/build/src/bundle.ts
- src/gui/package.json
- src/gui/scripts/prepare.js
- src/gui/src/index.tsx
- src/vlt/src/start-gui.ts
- src/vlt/test/start-gui.ts
This PR adds live reload to the GUI during local development by setting the environment variable `_VLT_DEV_LIVE_RELOAD`.
- Run the GUI watch script the same way that you currently do: `pnpm -F gui watch`
- When running the GUI locally set `_VLT_DEV_LIVE_RELOAD=1`
- Changes to `src/gui` will cause open browsers to `reload()`
When `_VLT_DEV_LIVE_RELOAD` is set, requests for gui assets will be proxied to the esbuild dev server instead of the static asset. In the browser an `EventSource` connection is opened which uses esbuild's builtin [live reload](https://esbuild.github.io/api/#live-reload) feature.
If the esbuild dev server is not running, then requests will fallback to the static asset like normal and message will be logged in the browser.
`_VLT_DEV_LIVE_RELOAD` has no effect on …
> dev(gui): add live reload

- src/vlt/src/start-gui.ts
- src/vlt/test/start-gui.ts
Ref https://github.com/vltpkg/vltpkg/pull/319#discussion_r1920876696
A not-great but ok-for-now way to remove an `eslint-disable-next-line`. The issue stems from unsafe code in the tests where we currently have a lot of lint rules disabled:
https://github.com/vltpkg/vltpkg/blob/a83e2d4cacbfc0a27ace040429522d42f9a8eced/eslint.config.mjs#L194-L199
Still don't think it's worth the effort to turn them on but something to keep in mind.
> test(start-gui): pass in values obj to match types

- src/gui/src/components/dashboard-grid/index.tsx
- src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
> fix(gui): text-overflow on dashboard item paths

- pnpm-lock.yaml
- src/package-json/package.json
- src/package-json/src/index.ts
- src/package-json/tap-snapshots/test/index.ts.test.cjs
- src/package-json/test/index.ts
Dependencies should be automatically sorted by name when saving a `package.json` file.
Fixes: https://github.com/vltpkg/vltpkg/issues/238
> package-json: sort dependencies by name

- src/gui/src/components/dashboard-grid/index.tsx
- src/gui/src/state/types.ts
- src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/dashboard-grid/index.tsx
- src/vlt/src/start-gui.ts
- Set a separate property for the shortened readable path value.
- Use the `readablePath` for the rendered path in the dashboard
while using `path` for navigating to different projects.
> gui: fix dashboard item selection

- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
updates text contrast for side items
Fixes #351
> gui side item text contrast

- src/gui/src/components/explorer-grid/result-item.tsx
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/result-item.tsx.snap
Copy/pasted the same code from #337
**Before**
**After**
> gui: fix ResultItem text overflow

- src/gui/src/components/queries/saved-item.tsx
- src/gui/test/components/queries/__snapshots__/saved-item.tsx.snap
- src/gui/test/components/queries/saved-item.tsx
Adds tooltip for the directory/context of the query to view untruncated text
Fixes #350
> query view directory tooltip

- infra/build/src/bundle.ts
- infra/build/src/transform-source.ts
Previously source rewriting was split between multiple esbuild
plugins which made it easier to read. However I did not realize
that onLoad esbuild plugins will bail once one plugin has claimed
a file. So if multiple plugins were trying to alter the source of
a single file then the first one registered would win.
This caused a recent refactor to no longer copy the gui assets to
the correct location during build because that file already had a
plugin that would operate on it first.
This is fixed by using a single esbuild onLoad plugin that is
responsible for all the source rewriting.
> build: move source rewriting to single esbuild plugin

- src/gui/src/components/explorer-grid/selected-item.tsx
I think this only happens in tests but `JSON.stringify(undefined)` is undefined so when it gets passed to `shiki.codeToHtml` from we get a lot of console.error output saying the `Cannot read properties of undefined (reading 'split')`.
Also TS doesn't help us here because JSON.stringify always returns a string according to it. So the easiest fix is to manually guard this and pass in an empty string instead.
Currently this is the output I get for the tests on `main`:
```
╰❯ pnpm -F gui test
> @vltpkg/gui@0.0.0-0 test /Users/lukekarrys/projects/vltpkg/vltpkg/src/gui
> vitest
DEV  v2.1.6 /Users/lukekarrys/projects/vltpkg/vltpkg/src/gui
stderr | src/components/ui/shiki.tsx:24:54
TypeError: Cannot read properties of undefined (reading 'split')
at splitLines …
```
> gui(test): quiet console.error for undefined manifests

- src/gui/src/components/explorer-grid/selected-item.tsx
- src/gui/test/components/explorer-grid/__snapshots__/selected-item.tsx.snap
Small design tweak / follow up from https://github.com/vltpkg/vltpkg/pull/368
> gui: fix render of non-registry dep-ids

- src/graph/src/ideal/get-importer-specs.ts
- src/graph/tap-snapshots/test/ideal/get-importer-specs.ts.test.cjs
- src/graph/test/ideal/get-importer-specs.ts
Fix a problem that made it impossible to install a dependency after uninstalling it.
Fixes: https://github.com/vltpkg/vltpkg/issues/294
> graph: fix reinstalling dependencies

- src/graph/src/graph.ts
- src/graph/tap-snapshots/test/graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/remove-nodes.ts.test.cjs
- src/graph/tap-snapshots/test/reify/optional-fail.ts.test.cjs
- src/graph/test/ideal/remove-nodes.ts
When removing a node from the graph using `Graph.removeNode` the
previous implementation would leave previous edges still registered
in the `Graph.edges` Set. This leaves edges in lockfiles after
uninstalling a package, e.g:
$ cat package.json
{
"name": "my-project",
"dependencies": {
"abbrev": "^3.0.0"
}
}
$ cat vlt-lock.json
{
"options": {},
"nodes": {
"··abbrev@3.0.0": [0,"abbrev","sha512-+/kfrslGQ7TNV2ecmQwMJj/B65g5KVq1/L3SGVZ3tCYGqlzFuFCGBZJtMP99wH3NpEUyAjn0zPdPUg0D+DwrOA=="]
},
"edges": {
"file·. abbrev": "prod ^3.0.0 ··abbrev@3.0.0"
}
}
$ vlt uninstall abbrev
$ cat vlt-lock.json
{
"options": {},
"nodes": {},
"edges": {
"file·. abbrev": "prod * ··abbrev@3.0.0"
}
}
This PR fixes it by making sure edges are removed from the
edge of sets whenever a node is removed from the graph. e.g: …
> graph: remove edge when removing node

- eslint.config.mjs
- infra/benchmark/test/index.ts
- src/git/test/spawn.ts
- src/graph/test/ideal/append-nodes.ts
- src/package-info/test/index.ts
- src/registry-client/test/index.ts
- src/tar/test/unpack-request.ts
- src/vlt/test/commands/config.ts
- src/which/test/index.ts
- src/workspaces/test/index.ts
- tap-config.yaml
Previously linting ignored floating promises from all tap function calls. Now only `t.test` and `t.skip` are allowed to not be `await`-ed.
There were some top-level `t.resolves` calls and similar that I chose to wrap in new `t.test` functions which is just a preference of mine.
This will either fix some flaky tests or rule out this being an issue with flaky tests.
Also bump the tap timeout to 10 minutes in the global tap config, because thats a really long time and I don't want our tests to ever fail for timeouts unless its an infinite loop or something.
> test: only allow floating promises from tap.[test|skip]

- eslint.config.mjs
- src/rollback-remove/src/remove.ts
- src/rollback-remove/test/index.ts
- src/vlt/src/commands/token.ts
- src/vlt/src/read-password.ts
From https://eslint.org/docs/latest/rules/no-control-regex
> Control characters are special, invisible characters in the ASCII range 0-31. These characters are rarely used in JavaScript strings so a regular expression containing elements that explicitly match these characters is most likely a mistake.
We're writing a CLI where these are not rarely used. And as a mistake it's unlikely and not worth the cost of ignoring it.
> allow control regex because this is a CLI

- pnpm-lock.yaml
- src/graph/src/actual/load.ts
- src/graph/src/browser.ts
- src/graph/src/dependencies.ts
- src/graph/src/edge.ts
- src/graph/src/graph.ts
- src/graph/src/ideal/append-nodes.ts
- src/graph/src/ideal/get-importer-specs.ts
- src/graph/src/lockfile/load-edges.ts
- src/graph/src/lockfile/types.ts
- src/graph/src/node.ts
- src/graph/src/reify/update-importers-package-json.ts
- src/graph/src/types.ts
- src/graph/test/dependencies.ts
- src/graph/test/ideal/add-nodes.ts
- src/graph/test/remove-optional-subgraph.ts
- src/gui/src/state/load-graph.ts
- src/package-json/package.json
- src/package-json/src/index.ts
- src/query/test/fixtures/graph.ts
- src/types/src/index.ts
- src/types/test/index.ts
- src/vlt/src/parse-add-remove-args.ts
- src/vlt/src/start-gui.ts
The goal here is to break a cycle between `graph` and `package-json` by moving the `DependencyType` related types and helpers to `@vltpkg/types`.
This is not strictly necessary as cycles are fine, but pnpm warns and turborepo (which we dropped) errors in this case. We already have to the types workspace to help alleviate issues like this, so I think these types/helpers are better suited to live there.
> types: move DependencyType related types to types workspace

- package.json
I added this previously as a shortcut to the common operation of preparing all the `src/*` workspaces.
But it should not be called `prepare` otherwise commands like `pnpm install` will run it which will end up preparing everything twice.
> rename root prepare script

- src/gui/src/components/dashboard-grid/table-columns.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
> fix: project column names & spec background color in light mode

- eslint.config.mjs
This fixes an issue where you could not run eslint from the GUI workspace (eg `pnpm -F gui lint`) since it has a different tsconfig than others. It still worked in CI because linting is run from the root in the ci.yml workflow.
A future optimization could filter which workspaces get linted based on what has changed, similar to what we do for tests. This is not a pressing need right now as linting and testing are run in parallel and linting is almost always finished before tests.
> lint: set correct tsconfig path for import/resolver when run from workspace

- eslint.config.mjs
I use `console.log` and `console.error` to debug tests sometimes and it usually takes me a minute to realize they are being `t.capture`'d so I won't see them. This is a lint rule for certain tests where we do this so it will warn with a message saying use another method.
> lint: warn with reminder about console.log/error in certain tests being captured

- src/gui/src/app/dashboard.tsx
- src/gui/src/lib/start-dashboard-data.ts
- src/gui/test/lib/__snapshots__/start-dashboard-data.ts.snap
- src/gui/test/lib/start-dashboard-data.ts
Refactored the logic to load dashboard data into its own helper method so that it can be reused in the create new project page. This refactor also makes it easier to start tests for it which are included here.
> gui: refactor start-dashboard-data

- src/vlt/src/start-gui.ts
- src/vlt/tap-snapshots/test/start-gui.ts.test.cjs
- src/vlt/test/start-gui.ts
Add a list of possible project locations to the `dashboard.json` data. This list may be used by the UI to propose locations to create new projects.
> vlt: add dashboard project locations data

- src/gui/src/components/explorer-grid/side-item.tsx
quick fix to prevent the ui from transitioning to an empty state after uninstall a dependency.
> bugfix: gui prevent uninstall redirect

- src/vlt/src/ignored-homedir-folder-names.ts
I store a ton of tests/demos/projects on my desktop & that may seem weird but I don't think I'm the only one. Most other ignored directories have an explicit usecase which is codified in their name but `"Desktop"` is a bit more ambiguous.
> fix: add back the desktop as a potential lookup location

- src/gui/src/components/dashboard-grid/index.tsx
- src/gui/src/lib/request-route-transition.ts
- src/gui/test/lib/request-route-transition.ts
Refactored the method used by the dashboard grid component to switch project into a reusable helper that can be used for other different backend interactions that will require a route change in the GUI.
> gui: refactor request route transition

- src/vlt/src/get-author-from-git-user.ts
- src/vlt/src/init.ts
- src/vlt/src/start-gui.ts
- src/vlt/tap-snapshots/test/init.ts.test.cjs
- src/vlt/tap-snapshots/test/start-gui.ts.test.cjs
- src/vlt/test/get-author-from-git-user.ts
- src/vlt/test/init.ts
- src/vlt/test/start-gui.ts
Add a `/create-project` endpoint that creates a new folder and sets up a new project using `init`.
> vlt: add start-gui create-project endpoint

- src/vlt/src/commands/install.ts
- src/vlt/src/commands/install/reporter.ts
This is a stop-gap to allow the CLI TypeScript source to be run completely with Node.
A future PR will revert this commit while also moving it to a new workspace that will require building in order to compile the JSX to JS.
I'll do this the next time I add a new `ink` based reporter.
> install: dont use tsx for now

- src/gui/src/components/dashboard-grid/index.tsx
- src/gui/src/components/explorer-grid/empty-results-state.tsx
- src/gui/src/components/explorer-grid/index.tsx
- src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/empty-results-state.tsx.snap
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
Changes the class on the container from being a margin to padding which resolves the whitespace issue where you'd see the background at the bottom of the page.
> fix: margin bottom issues where background is visible

- src/vlt/src/project-info.ts
- src/vlt/src/start-gui.ts
- src/vlt/tap-snapshots/test/project-info.ts.test.cjs
- src/vlt/tap-snapshots/test/start-gui.ts.test.cjs
- src/vlt/test/project-info.ts
- src/vlt/test/start-gui.ts
Extracted the bits responsible for retrieving project info into a separate `src/vlt/src/project-info.ts` module.
Added a `projectInfo` to `graph.json` to provide the GUI info on whether the current explored project is installed using the vlt client and other associated tools.
> vlt: refactor start-gui project-info

- src/gui/src/app/explorer.tsx
- src/gui/src/components/explorer-grid/setup-project.tsx
- src/gui/src/state/index.ts
- src/gui/src/state/types.ts
- src/gui/test/app/__snapshots__/explorer.tsx.snap
- src/gui/test/app/explorer.tsx
- src/gui/test/components/explorer-grid/__snapshots__/setup-project.tsx.snap
- src/gui/test/components/explorer-grid/index.tsx
- src/gui/test/components/explorer-grid/setup-project.tsx
- src/gui/test/state/load-graph.ts
For projects that are not installed using the vlt client, the GUI will now render a view that allows users to run an initial `vlt install` prior to navigating to the explore dependencies view.
> gui: add setup project

- .github/workflows/publish.yml
- infra/benchmark/package.json
- infra/benchmark/src/download.ts
- infra/benchmark/src/index.ts
- infra/benchmark/test/index.ts
- infra/build/package.json
- package.json
- pnpm-lock.yaml
- scripts/consistent-package-json.js
- scripts/make-dist-bins.js
- src/cache-unzip/package.json
- src/gui/package.json
- src/package-info/package.json
- src/package-info/scripts/benchmark.js
- src/pick-manifest/package.json
- src/pick-manifest/scripts/benchmark.js
- src/semver/benchmarks/this.js
- src/semver/package.json
- src/spec/package.json
- src/spec/scripts/benchmark.js
- src/tar/package.json
- src/tar/scripts/benchmark.js
This removes more instances of calling `dist/esm/*` files and instead calling their TS source counterparts.
> scripts: run source TS files directly

- src/gui/src/components/explorer-grid/index.tsx
Fixes an issue found when clicking on dependents.
Previously clicking on the root node would take you to:
`http://localhost:7017/explore?query=%3Aroot%20`
Now it takes you to:
`http://localhost:7017/explore?query=%3Aroot`
> gui: queries should be always trimmed

- src/query/src/attribute.ts
- src/query/src/class.ts
- src/query/src/combinator.ts
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/types.ts
- src/query/test/attribute.ts
- src/query/test/fixtures/selector.ts
- src/query/test/index.ts
`Query.search()` now accepts an `AbortSignal` that allows for cancelling ongoing operations. This is going to be very useful in order to support pseudo selectors that fetch external data but also it should make for a more responsive UI when using in the GUI by cancelling any previous / ongoing search.
Refs: https://github.com/vltpkg/vltpkg/issues/360
> query: add ability to cancel search

- src/gui/src/components/explorer-grid/add-dependencies-popover.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/src/components/ui/popover.tsx
- src/gui/test/components/explorer-grid/__snapshots__/add-dependencies-popover.tsx.snap
- src/gui/test/components/ui/__snapshots__/popover.tsx.snap
When adding a new dependency, the dropdown selector for the dependency type is currently hidden behind the container background. This changeset fixes it so that the dependency type selection is visible.
> gui: fixes visibility of dep type selection

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/graph/package.json
- src/semver/benchmarks/this.js
- src/vlt/package.json
- src/vlt/src/commands/gui.ts
- src/vlt/src/ignored-homedir-folder-names.ts
- src/vlt/src/read-project-folders.ts
- src/vlt/src/start-gui.ts
- src/vlt/tap-snapshots/test/ignored-homedir-folder-names.ts.test.cjs
- src/vlt/tap-snapshots/test/read-project-folders.ts.test.cjs
- src/vlt/test/commands/gui.ts
- src/vlt/test/read-project-folders.ts
- src/vlt/test/start-gui.ts
start-gui tests should not lookup the actual file system on its tests. Instead we should mock these internal calls to have a deterministic and faster way to run these tests in different systems.
> vlt: mock file system lookup on start-gui tests

- src/gui/src/components/explorer-grid/setup-project.tsx
When the "Install dependencies" button is clicked, the footer moves to the top.
> gui: fix `LoadingSpinner` height

- src/vlt/src/output.ts
- src/vlt/test/output.ts
Fixes #465
**before**
```sh
╰❯ pnpm -s vlt gui
Promise { <pending> }
⚡️ vlt GUI running at http://localhost:7017
Opening a web browser to: http://localhost:7017/explore?query=%3Aroot
```
**after**
```sh
╰❯ pnpm -s vlt gui
⚡️ vlt GUI running at http://localhost:7017
Opening a web browser to: http://localhost:7017/explore?query=%3Aroot
```
> cli: await view fn since it can be async

- src/gui/src/app/explorer.tsx
- src/gui/test/components/explorer-grid/index.tsx
- src/query/README.md
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/outdated.ts
- src/query/src/types.ts
- src/query/tap-snapshots/test/pseudo/outdated.ts.test.cjs
- src/query/test/attribute.ts
- src/query/test/fixtures/graph.ts
- src/query/test/fixtures/selector.ts
- src/query/test/index.ts
- src/query/test/pseudo/outdated.ts
- src/query/test/pseudo/semver.ts
- src/vlt/src/commands/list.ts
- src/vlt/src/commands/query.ts
Add a new `:outdated()` pseudo selector to the query language.
It supports a `type` parameter that can be one of the following values:
- `any` (default) a version exists that is greater than the current one
- `in-range` a version exists that is greater than the current one, and satisfies at least one if its parent's dependencies
- `out-of-range` a version exists that is greater than the current one, does not satisfy at least one of its parent's dependencies
- `major` a version exists that is a semver major greater than the current one
- `minor` a version exists that is a semver minor greater than the current one
- `patch` a version exists that is a semver patch greater than the current one
Example:
Selects any package that has a greater version published to its
configured registry: …
> query: add outdated pseudo selector

- .github/workflows/publish.yml
- .github/workflows/release.yml
- infra/build/src/bin/publish.ts
This is another step towards reproducible builds.
This PR creates a `release.yml` workflow which will run on commits to main. For the latest commit to main it will create or update a release PR with the `src/vlt/package.json` version bumped to `0.0.0-$INCREMENTED_PRERELEASE_NUMBER`.
When that PR is merged it will publish that version the same way the current `publish.yml` workflow does when run manually.
Once this lands and works, the publish.yml workflow can be removed. But since GitHub actions are difficult to test it is kept around for publishing purposes.
> publish: create release workflow

- src/graph/src/reify/update-importers-package-json.ts
- src/graph/tap-snapshots/test/reify/update-importers-package-json.ts.test.cjs
- src/graph/test/reify/update-importers-package-json.ts
Fixes using the correct spec to `package.json` when using aliases on `vlt install` 
e.g: `vlt install underscore@npm:lodash`
Fixes: https://github.com/vltpkg/vltpkg/issues/390
> vlt: save aliases to package.json

- infra/build/src/prepack.ts
- infra/build/test/prepack.ts
I broke the published `vlt` package in #481 by accidentally removing the `package.json#bin`. This adds them back.
> cli: ensure published package.json has bins set

- .github/workflows/release.yml
- scripts/tgz-ssri.js
The goal is to make it easier to see integrity of each package as the release PR gets regnerated and to compare against the integrity of the published packages once the PR gets merged.
So far I've seen some packages get different integrity values when packed vs published and this will make it easier to track that (manually for now).
> release: list integrity next to package name/version

- src/gui/src/app/queries.tsx
- src/gui/src/components/create-new-project/index.tsx
- src/gui/src/components/directory-select.tsx
- src/gui/src/components/queries/create-query.tsx
- src/gui/src/components/queries/queries-empty-state.tsx
- src/gui/src/components/queries/saved-item.tsx
- src/gui/test/app/__snapshots__/queries.tsx.snap
- src/gui/test/app/queries.tsx
- src/gui/test/components/__snapshots__/directory-select.tsx.snap
- src/gui/test/components/create-new-project/__snapshots__/index.tsx.snap
- src/gui/test/components/create-new-project/index.tsx
- src/gui/test/components/directory-select.tsx
- src/gui/test/components/queries/__snapshots__/create-query.tsx.snap
- src/gui/test/components/queries/create-query.tsx
- src/gui/test/components/queries/saved-item.tsx
Replaces the old directory select logic, which was previous just an input field with a command/combobox that allows a user to select the directory from a list.
This PR creates a new `directory-select` component to reuse whenever the UI requires it.
Closes vltpkg/statusboard#84
- **feat**: creates `directory-select` component
- removes old path select, replaces with directory-select component
- updates queries saved-item with new `directory-select` comp
- updates `queries` view to fetch dashboard data
- updates directory select logic for new `directory-select` comp
- fetches dashboardData to pass into `create-query` comp
- chore: lint & format
> gui: update directory select logic

- src/gui/src/components/navigation/sidebar/nav-project-queries.tsx
- src/gui/test/components/navigation/sidebar/nav-project-queries.tsx
Fixes #521
- if `sidebar` state is `closed` and a query selection is pressed, the
`sidebar` state is changed to `open`
- in a `useEffect`, if the `sidebar` state is changed to `closed`, the
query dropdown collapse
> gui: bugfix sidebar button click

- src/gui/src/app/error-found.tsx
- src/gui/test/app/__snapshots__/error-found.tsx.snap
- src/gui/test/app/error-found.tsx
- correctly sets the navigation destination on the `dashboard` button
- updates the height of the view if the `pathname` is not `/error`, this
is to support a global errorBoundary view
> gui: error view button bugfix

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/security-archive/LICENSE
- src/security-archive/README.md
- src/security-archive/package.json
- src/security-archive/src/browser.ts
- src/security-archive/src/index.ts
- src/security-archive/src/types.ts
- src/security-archive/tap-snapshots/test/index.ts.test.cjs
- src/security-archive/test/browser.ts
- src/security-archive/test/fixtures/graph.ts
- src/security-archive/test/index.ts
- src/security-archive/tsconfig.json
- src/security-archive/typedoc.mjs
Add a new package `@vltpkg/security-archive` that handles accessing, fetching remote data and persisting security report data on packages from a given graph.
```js
import { actual } from '@vltpkg/graph'
import { SecurityArchive } from '@vltpkg/security-archive'
const specOptions = {
registry: 'https://registry.npmjs.org/',
}
const graph = actual.load({
...specOptions,
projectRoot: process.cwd(),
})
const archive = await SecurityArchive.start({ graph, specOptions })
if (archive.ok) {
for (const node of graph.nodes.values()) {
const securityData = archive.get(node.id)
if (securityData) {
console.log('securityData', securityData)
}
}
} else {
console.warn('Failed to start the SecurityArchive')
}
```
> security-archive: add a security db & cache system

- src/dep-id/src/index.ts
- src/dep-id/tap-snapshots/test/index.ts.test.cjs
- src/dep-id/test/index.ts
- src/graph/src/node.ts
- src/graph/test/node.ts
I stumbled across a couple of edge case scenarios that were breaking query functionality that were caused by random packages in a large install having `manifest.version` values with a prefixed v, e.g: `"version": "v1.2.3"`
This PR:
- Removes any preppending `v` from a `node.version` value.
- The `getId` method now removes any preppending `v` value from the resulting `DepID` when reading from a manifest.
> normalize version values

- src/gui/src/components/navigation/sidebar/nav-project-queries.tsx
- src/gui/src/state/index.ts
- src/gui/test/components/navigation/sidebar/nav-project-queries.tsx
- **bugfix**: listens to `popstate` event to track state `query`
- **bugfix**: hides ProjectQueries if the !`pathname` includes '/explore'
> gui: router history bugfix

- pnpm-lock.yaml
- src/security-archive/src/index.ts
- src/security-archive/test/index.ts
This PR updates the nested dep `is-core-module` to the latest version `2.16.1` which includes a fix to properly detect `node:sqlite` as being available to Node 22 (https://github.com/inspect-js/is-core-module/commit/aafb7cae0976ecfb156bc563dde57ca8fd838d0c)
> lint: update is-core-module

- src/vlt/package.json
- src/vlt/src/start-gui.ts
- src/vlt/test/start-gui.ts
This is not the first time this has broken which means it definitely needs a test but that is blocked by #456. I've confirmed this fix works for me locally and will test that the GUI works when bundled/compiled as part of fixing #456.
> build: read gui assets dir from env in builds

- infra/build/src/bundle.ts
- infra/build/src/compile.ts
Previously `esbuild` was used for setting globals and converting to `node:` prefixed imports so that `deno compile` would work. This PR opts in to using deno's `--unstable-node-globals` and `--unstable-bare-node-builtins` flags since they do the same thing.
> compile: use deno --unstable flags instead of rolling our own

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .nvmrc
- CONTRIBUTING.md
`nvm` does not understand all of npm-style semver range selectors (specifically `"^"`). The current range `^22.14.0` fails to be parsed & errors accordingly (although this _does_ work in CI because `setup-node` manually reads from & then evaluates this value using `node-semver`). This PR switches the value back to something `nvm` understands while trying to stay as close to the intent of the original change.
- switch nvm to use `lts/jod` which is the "latest" `22` release line
- switch our workflows to use `node-version` config which _does_ support npm-style semver range selectors
- document these changes in `CONTRIBUTING.md`
> fix: `nvm` doesn't understand `"^"` `node-semver` range selectors

- pnpm-lock.yaml
- src/registry-client/package.json
@darcyclarke reported a deno crash with the following stack:
```
error: Uncaught TypeError: fastNowTimeout.refresh is not a function
fastNowTimeout.refresh();
^
at refreshTimeout (file:///var/folders/gd/1pffxr4d603251w7w1q_cb_40000gn/T/deno-compile-vlt/chunk-06ZDSGAE.js:1863:24)
at onTick (file:///var/folders/gd/1pffxr4d603251w7w1q_cb_40000gn/T/deno-compile-vlt/chunk-06ZDSGAE.js: 1858:9)
at callback (ext: deno_web/02_timers. js:58:7)
at eventLoopTick (ext:core/01_core.js:212:13)
```
This code lives in undici, so I think updating undici to the latest version will make it easier to triage future bugs/crashes like this.
> registry-client: update to undici@7

- src/query/README.md
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/malware.ts
- src/query/tap-snapshots/test/pseudo/malware.ts.test.cjs
- src/query/test/pseudo/malware.ts
Add a `:malware(<kind>)` selector that filters nodes based on malware-related alert types from the security-archive.
> query: add malware selector

- src/security-archive/src/index.ts
The `GROUP BY depID HAVING SUM(...)` phrase means:
- Get all the records for a given depID, and group them by depID
- For each depID, add up the sum all of the `start + ttl` values of the records in that group.
- If the sum of _all_ those values is greater than `now`, include the entire group.
As `depID` is a unique key on that table, grouping by it has no effect, because there can only ever be a single record for a given `depID`. But, if that is ever not the case (for example, if we start tracking reports from multiple sources separately, have records for each CVE, etc.), then this will result in never expiring any items that have more than one record!
For example, imagine that there are two records for a given depID, which are both fetched at `1743000000000`, each having a 24 hour TTL …
> security-archive: fix incorrect SQL

- src/security-archive/src/index.ts
The value returned by the sqlite time method is still in seconds even when you add subsecond precision, this change will make sure it's normalized to ms so that the ttl check works as intended.
> security-archive: fix cache ttl check

- src/query/README.md
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/severity.ts
- src/query/tap-snapshots/test/pseudo/severity.ts.test.cjs
- src/query/test/pseudo/severity.ts
Add a `:severity(<kind>)` / `:sev(<kind>)` selector that filters nodes based on license-related alert types from the security-archive.
> query: add severity selector

- src/query/README.md
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/squat.ts
- src/query/tap-snapshots/test/pseudo/squat.ts.test.cjs
- src/query/test/pseudo/squat.ts
Add a `:squat(<kind>)` selector that filters nodes based on squat-related alert types from the security-archive.
> query: add squat selector

- src/cli-sdk/src/commands/list.ts
- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/query.ts
We can avoid loading security data in case no security selector was used in one of the cli commands. e.g: `vlt ls`, `vlt query`
> cli-sdk: fix skipping security data

- src/query/README.md
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/cve.ts
- src/query/tap-snapshots/test/pseudo/cve.ts.test.cjs
- src/query/test/pseudo/cve.ts
- src/security-archive/src/types.ts
Adds a new `:cve(<id>)` selector that filters packages based on a given cve id.
> query: add cve selector

- src/query/src/pseudo/malware.ts
- src/query/src/pseudo/severity.ts
- src/query/src/pseudo/squat.ts
The `:malware()`, `:severity()` and `:squat()` selectors need to remove from the partially selected results any edges that are pointing to missing packages, similar to the other security selectors.
> query: fix removing dangling edges

- src/query/README.md
- src/query/src/pseudo.ts
- src/query/src/pseudo/cwe.ts
- src/query/tap-snapshots/test/pseudo/cwe.ts.test.cjs
- src/query/test/pseudo/cwe.ts
- src/security-archive/src/types.ts
Add a `:cwe(<id>)` selector that filters packages by a given cwe id.
> query: add cwe selector

- infra/smoke-test/test/cache-unzip.ts
- src/cache-unzip/src/index.ts
- src/cache-unzip/src/unzip.ts
This change ensures that cache unzipping works on Windows when compiled.
> cache-unzip: pass internal main path as file url

- src/cli-sdk/package.json
- src/cli-sdk/src/index.ts
- src/gui/package.json
- src/server/package.json
- www/docs/typedoc.workspace.mjs
Previously the GUI was marked as private so that it wouldn't appear in the
generated typedoc docs. But now that we are publishing workspaces, if the
GUI is private then anything that depends on it would need to be private
also. It's easier to make everything public and publishable and not worry
about it.
The GUI is now excluded from generated docs since it has no observable
exports.
> gui: dont mark as private in package.json

- infra/smoke-test/test/rollback-remove.ts
- src/cache-unzip/src/index.ts
- src/cache-unzip/test/index.ts
- src/rollback-remove/src/index.ts
- src/rollback-remove/src/remove.ts
- src/rollback-remove/test/index.ts
This does for `rollback-remove` what #553 and #564 and did for `cache-unzip`.
Now that this pattern is better established it also adds some tests for it in both `cache-unzip` and `rollback-remove`.
It also adds a smoke test to assert that `rollback-remove` runs successfully when compiled by installing two different versions of the same package by-to-back and testing that the old version has no `.VLT.DELETE.` files left behind.
> fix `rollback-remove` when compiled

- infra/build/src/bundle.ts
- pnpm-lock.yaml
- src/cli-sdk/package.json
With the latest version of ink we no longer need to manually
copy the yoga.wasm file to our bundled directory
> install: update ink

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/smoke-test.yml
- infra/smoke-test/package.json
- infra/smoke-test/test/cache-unzip.ts
- infra/smoke-test/test/fixtures/after.ts
- infra/smoke-test/test/fixtures/before.ts
- infra/smoke-test/test/fixtures/run.ts
- infra/smoke-test/test/fixtures/variants.ts
- infra/smoke-test/test/install.ts
- infra/smoke-test/test/postinstall.ts
- infra/smoke-test/test/rollback-remove.ts
- pnpm-lock.yaml
The smoke tests were previously flaky for two reasons:
- Errors when cleaning up all the generated fixtures
- Timeouts where a spawned `vlt` command would hang
This PR works around those two issues by setting `save-fixture: true` and `jobs: 1` in the tap config.
It's worth noting that the errors when cleaning up fixtures doesn't point to any real bugs in vlt, it's just hard for CI to reliably delete 1000s of files especially when we have detached processes that might be operating on those files.
But the spawned processes hanging *might* point to a real bug, but I was unable to pinpoint it. There's no reason the smoke tests shouldn't be able to run in parallel. Each spawned command is given it's own directory and isolated by setting `HOME` and `XDG_*` environment variables. I was also …
> smoke-test: reduce flakes

- src/query/src/index.ts
- src/query/src/pseudo/cve.ts
- src/query/src/pseudo/cwe.ts
- src/query/src/types.ts
- src/query/test/index.ts
- src/query/test/pseudo/cve.ts
- src/security-archive/src/types.ts
Adds a new `insights` object to each node in the query search
response that contains metadata parsed from the security archive.
Fixes: https://github.com/vltpkg/vltpkg/issues/597
> query: add insights to query response node

- infra/smoke-test/test/install.ts
This is non-deterministic due to how TTYs output. We are already testing
that the output matches what we expect, but we dont need to check that
each variant has the exact same output.
Should fix this flaky smoke-test run: https://github.com/vltpkg/vltpkg/actions/runs/14143455312/job/39627874959#step:9:713
> smoke-test: dont match tty output across variants

- src/query/src/index.ts
- src/query/src/pseudo/cve.ts
- src/query/src/pseudo/cwe.ts
- src/security-archive/src/types.ts
Fixes an issue with not being able to read results due to logic that tries to read properties from an undefined value. Type definition for the resulting package alert object is fixed and so its usage in `@vltpkg/query`.
> fix `vlt query` results

- src/query/src/index.ts
- src/query/src/types.ts
Adds a `QueryResponseEdge` type so that both the `nodes` and `edges` returned from `query.search()` can have a unified type definition.
> query: fix query response types

- src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
- src/graph/src/visualization/human-readable-output.ts
- src/graph/tap-snapshots/test/visualization/human-readable-output.ts.test.cjs
- src/graph/test/visualization/human-readable-output.ts
Fix the representation of aliased dependencies and custom registry prefixes in the human readable output.
The registry prefix now goes along with the node name/version instead of prefixing the dependency name.
For a given `package.json` file:
```json
{
"name": "my-project",
"dependencies": {
"a": "npm:abbrev@^3.0.0"
}
}
```
```
vlt ls
my-project
└── npm:a (abbrev@3.0.0)
```
```
vlt ls
my-project
└── a (npm:abbrev@3.0.0)
```
> graph: fix aliases in human readable output

- pnpm-lock.yaml
- src/cache/src/index.ts
- src/cache/test/index.ts
- src/cli-sdk/package.json
- src/cli-sdk/src/commands/cache.ts
- src/cli-sdk/src/commands/whoami.ts
- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/src/config/usage.ts
- src/cli-sdk/tap-snapshots/test/commands/cache.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
- src/cli-sdk/test/commands/cache.ts
- src/cli-sdk/test/commands/whoami.ts
- src/cli-sdk/test/index.ts
- src/package-info/src/index.ts
- src/registry-client/src/cache-entry.ts
- src/registry-client/src/index.ts
- src/registry-client/tap-snapshots/test/cache-entry.ts.test.cjs
- src/registry-client/test/cache-entry.ts
- src/registry-client/test/index.ts
- src/spec/src/browser.ts
```
Usage:
vlt cache <command> [flags]
Work with vlt cache folders
Subcommands
add
Resolve the referenced package identifiers and ensure they are cached
​vlt cache add <package-spec> [<package-spec>...]
ls
Show cache entries
​vlt cache ls [<key>...]
clean
Purge expired cache entries
​vlt cache clean [<key>...]
delete
Purge items explicitly, whether expired or not
​vlt cache delete <key> [<key>...]
delete-before
Purge all cache items from before a given date
​vlt cache delete-before <date>
delete-all
Delete the entire cache folder to make vlt slower
​vlt cache delete-all
```
> add 'vlt cache' command

- src/gui/src/components/explorer-grid/index.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/src/components/explorer-grid/types.ts
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
- src/gui/test/components/explorer-grid/side-item.tsx
Fixes displays spec info on side items for dependencies types other than registry (namely: git, file, remote & workspaces) and adds a new interface for displaying the proper dependency name of aliased dependencies.
Fixes: https://github.com/vltpkg/vltpkg/issues/352
> gui: fixes side item info

- src/gui/src/app/explorer.tsx
- src/gui/src/components/navigation/header.tsx
- Fixes a bug where the header title is not immediately visible when starting the gui on the `explore` route,
the cause was a check for if the project was installed with vlt.
- Optimizes the header component by removing state and useEffect, and using a useMemo instead, which improves re-rendering on the header component itself.
> gui: bugfix initial header load

- src/query/src/pseudo.ts
- src/query/test/index.ts
So that you can do stuff like:
```
#minimatch:v(3)
#abbrev:v(3.0.0)
#react:v(17 || 18)
```
> query: add v as shortcut to semver

- src/cli-sdk/src/parse-add-remove-args.ts
- src/cli-sdk/tap-snapshots/test/parse-add-remove-args.ts.test.cjs
- src/graph/src/dependencies.ts
- src/graph/src/graph.ts
- src/graph/src/ideal/add-nodes.ts
- src/graph/src/reify/update-importers-package-json.ts
- src/graph/src/resolve-save-type.ts
- src/graph/tap-snapshots/test/ideal/add-nodes.ts.test.cjs
- src/graph/tap-snapshots/test/reify/update-importers-package-json.ts.test.cjs
- src/graph/test/dependencies.ts
- src/graph/test/graph.ts
- src/graph/test/ideal/add-nodes.ts
- src/graph/test/reify/update-importers-package-json.ts
- src/graph/test/resolve-save-type.ts
- src/types/src/index.ts
- When a `--save-*` config is not provided, deps will be saved to either
their current state, or `'prod'` if they are not already a dependency.
- Handling of `peerOptional` dependencies is added.
Fix: #552
cc: @ejkorol
> graph: properly save dependency types to manifests

- src/cache-unzip/src/unzip.ts
- src/cache-unzip/test/unzip.ts
When unzipping cache entries we use the modulo operator to know when we are reading a header key or value.
Previously this operation was accidentally being performed on the offset which was only passing tests by coincidence that the keys and values were even lengths.
This commit makes sure we are checking the length of the headers array instead and adds some oddly length-ed headers to the test.
> cache-unzip: properly read length/encoding headers

- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
- src/cli-sdk/test/commands/query.ts
- src/cli-sdk/test/config/definition.ts
Add a new `--expect-results` config value that when used with the `vlt query` command allows for validation of the result values of a query.
Example:
vlt query --expect-results=">=1"
my-project
└── a@1.0.0
vlt query --expect-results=false
Error: Unexpected number of items
at ...
[cause]: { found: 1, wanted: 0 }
}
Fixes: https://github.com/vltpkg/vltpkg/issues/592
> cli-sdk: add expect-results config

- infra/smoke-test/test/cache-unzip.ts
- pnpm-lock.yaml
- src/cache-unzip/package.json
- src/cache-unzip/src/unzip.ts
- src/cache-unzip/test/unzip.ts
With this change the `cache-unzip` process will now link any existing integrity files to the unzipped cache entry.
I tried a different approach to this originally where `@vltpkg/cache.set` was responsible for updating the integrity files. But we already use `cache.set(key, val, { integrity })` to mean "write this value to the cache, first linking *from* the integrity file if it exists" which is the behavior we want everywhere else.
So rather than make a new method/option on `@vltpkg/cache` for this less used behavior, `cache-unzip` uses the `cache.path()` and `cache.integrityPath()` methods to manually re-link any integrity files.
Fixes #617
> cache-unzip: write unzipped result to existing integrity files

- src/query/README.md
- src/query/src/pseudo.ts
- src/query/src/pseudo/published.ts
- src/query/tap-snapshots/test/pseudo/published.ts.test.cjs
- src/query/test/pseudo/published.ts
Adds a `:published("<date>")` pseudo selector that matches packages based on their publication date.
The date parameter can be prefixed with a comparator (>, <, >=, <=). If no comparator is provided, it will match exact dates.
Examples:
/* Matches packages published exactly on January 1st, 2024 */
:published(2024-01-01)
/* Matches packages published after January 1st, 2024 */
:published(">2024-01-01")
/* Matches packages published on or before December 31st, 2023 */
:published("<=2023-12-31")
Fixes: https://github.com/vltpkg/statusboard/issues/107
> query: add published selector

- src/gui/src/components/explorer-grid/selected-item/tabs-insight.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-manifest.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-versions.tsx
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-insight.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-manifest.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-versions.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/tabs-insight.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-manifest.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-versions.tsx
Consistently renders a button for each `tab-content` on the selected item in the gui, and renders an empty state when applicable.
Closes vltpkg/statusboard#99
- **`tabs-insights`** consistent render with empty state
- **`tabs-manifest`** consistent render with empty state
- **`tabs-versions`** consistent render with empty state
> gui: selected item tabs consistent render

- src/query/README.md
- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/score.ts
- src/query/tap-snapshots/test/pseudo/score.ts.test.cjs
- src/query/test/pseudo/score.ts
Adds a `:score("<rate>", [kind])` pseudo selector that matches packages based on the scores rated found in the insights data.
The `rate` parameter can be prefixed with a comparator (>, < , >=, <=, similar to the `:published` selector in order to compare against a range instead of comparing exact values. If no comparator is provided, it will match exact scores.
Note that `rate` values are percentual values and can be either 0-1 or 0-100 and will be normalized prior to comparison.
Examples:
/* Matches packages with exactly 0.8 overall score */
:score(80)
/* Matches packages with overall score greater than 0.8 */
:score(">0.8")
/* Matches maintenance score less than or equal to 0.5 */
:score("<=0.5", "maintenance")
> query: add score selector

- src/query/src/pseudo.ts
- src/query/src/pseudo/empty.ts
- src/query/tap-snapshots/test/pseudo/empty.ts.test.cjs
- src/query/test/pseudo/empty.ts
Refactor `:empty` into its own file and add unit tests for it.
> query: refactor empty pseudo selector

- src/query/src/pseudo.ts
- src/query/src/pseudo/missing.ts
- src/query/tap-snapshots/test/pseudo/missing.ts.test.cjs
- src/query/test/pseudo/missing.ts
Refactor `:missing` into its own file and add unit tests for it.
> query: refactor missing pseudo selector

- src/query/src/pseudo/attr.ts
- src/query/tap-snapshots/test/pseudo/attr.ts.test.cjs
- src/query/test/pseudo/attr.ts
Add tests for the `:attr()` selector and adds support to naming properties using quoted strings, e.g:
:attr("scripts", [test])
> query: add tests for the attr selector

- src/gui/src/components/explorer-grid/selected-item/tabs-insight.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-manifest.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-versions.tsx
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-insight.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-manifest.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-versions.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/tabs-insight.tsx
Fixes a bug where the `selected-item` may have no insights, yet have a package score.
Creates an explicit message on the empty state, where the package could either be `scanned` with no insights, or the package may not have any insights available.
Creates snapshot tests for this state
Also, links the socket external link to the actual package
> gui: bugfix `selected-item` no insights with a package score

- src/query/src/pseudo/published.ts
- src/query/tap-snapshots/test/pseudo/missing.ts.test.cjs
The `:published` selector needs the full packument in order to retrieve the publish date / time.
> query: fix metadata for published selector

- src/cli-sdk/src/commands/cache.ts
- src/cli-sdk/src/config/index.ts
- src/cli-sdk/src/output.ts
- src/cli-sdk/src/print-err.ts
- src/cli-sdk/src/view.ts
- src/cli-sdk/tap-snapshots/test/config/index.ts.test.cjs
- src/cli-sdk/test/commands/cache.ts
- src/cli-sdk/test/config/index.ts
- src/cli-sdk/test/output.ts
- src/cli-sdk/test/print-err.ts
- src/error-cause/src/index.ts
#579 without any of the significant changes to `error-cause`.
If we are printing any `Error` without a handled code (whether from `error-cause` or not), we now print all the information from the error including the stack. But we cap each printed bit of information at 200 lines to avoid blowing up the terminal.
Also uses `util.format` everywhere with common options from `view` so we get colors.
> cli-sdk: more comprehensive error messaging

- src/query/src/parser.ts
- src/query/test/parser.ts
When escaping slashes for scoped names, we need to also take into account that names can contain dashes and dots, e.g:
#@scope-name/pkg
> query: fix parsing scope names with dashes in ids

- src/cli-sdk/src/exec-command.ts
- src/cli-sdk/src/print-err.ts
- src/error-cause/src/index.ts
- src/error-cause/test/index.ts
- src/package-info/src/index.ts
- src/package-json/src/index.ts
- src/promise-spawn/src/index.ts
- src/registry-client/src/cache-entry.ts
- src/spec/src/browser.ts
This removes the `isErrorRoot` type guard in favor of a new one `isErrorWithCode`. This better matches what is actually being done with the type guard in `print-err`.
Previously it was only checking if the error had a cause that was an object, but asserting that the cause was one thrown by `@vltpkg/error-cause`. Now it is checking if the code is one of our known codes.
This also takes any `cause.cause` (which has to be `unknown` for compatability with TS) and converts it to an `Error` and updates the resulting types appropriately.
> error-cause: more generic type checks

- src/gui/src/components/query-bar/index.tsx
- src/gui/src/components/query-bar/query-token.tsx
- src/gui/test/components/query-bar/__snapshots__/query-highlighter.tsx.snap
- src/gui/test/components/query-bar/query-highlighter.tsx
- src/query/src/index.ts
- src/query/src/parser.ts
- src/query/test/index.ts
In order to more easily account for escaped characters the token creation is now done at the parser module that handles the escaping and unescaping of reserved characters.
> gui: fix query highlight

- infra/smoke-test/test/fixtures/variants.ts
- scripts/bins/vlr.ps1
- scripts/bins/vlrx.ps1
- scripts/bins/vlt.ps1
- scripts/bins/vlx.ps1
- scripts/bins/vlxl.ps1
- src/rollback-remove/src/index.ts
- src/rollback-remove/test/index.ts
08c61365a7f92472082987f358df7a6702e94c59 fixed a bug where edges in were not being deleted when their parent node was deleted. This caused the `rollback-remove` instance to attempt to rename the same path twice, which was causing `EPERM` errors on Windows the 2nd time.
I was able to reproduce this consistently by running (with no node_modules/cache/lockfile) `vlt i abbrev@2.0.0` followed by `vlt i abbrev@3.0.0`.
01e8a34776fc2714f749f33b10d01d14aab74dfc fixed this error by treating `EPERM` errors the same as `ENOENT` but this caused the temporary `.VLT.DELETE.*` rollback files to never be removed which was causing the smoke-test to fail.
This PR keeps the handling of EPERM errors, because without it we get a lot of flaky tests. But it avoids this specific cause of this EPERM error by using …
> windows smoke test fixes

- src/query/src/parser.ts
- src/query/src/pseudo/malware.ts
- src/query/src/pseudo/published.ts
- src/query/src/pseudo/score.ts
- src/query/src/pseudo/semver.ts
- src/query/src/pseudo/severity.ts
- src/query/src/pseudo/squat.ts
- src/query/src/types.ts
- src/query/tap-snapshots/test/parser.ts.test.cjs
- src/query/tap-snapshots/test/pseudo/malware.ts.test.cjs
- src/query/tap-snapshots/test/pseudo/published.ts.test.cjs
- src/query/tap-snapshots/test/pseudo/score.ts.test.cjs
- src/query/tap-snapshots/test/pseudo/semver.ts.test.cjs
- src/query/tap-snapshots/test/pseudo/severity.ts.test.cjs
- src/query/tap-snapshots/test/pseudo/squat.ts.test.cjs
- src/query/test/parser.ts
- src/query/test/pseudo/malware.ts
- src/query/test/pseudo/published.ts
- src/query/test/pseudo/score.ts
- src/query/test/pseudo/semver.ts
- src/query/test/pseudo/severity.ts
- src/query/test/pseudo/squat.ts
- Added a new step to the query `parse` method that cleans up any usage of combinators within the pseudo selectors that accept comparator characters, 
- support unquoted params in semver selector, e.g: `:semver(>2.0.0)`
- support unquoted params in published selector, e.g: `:published(>2024)`
- support unquoted params in score selector, e.g: `:score(>=50)`
- support comparison params in malware selector, e.g: `:malware(<1)`
- support comparison params in severity selector, e.g: `:severity(>=0)`
- support comparison params in squat selector, e.g: `:squat(<=2)`
Replaces: https://github.com/vltpkg/vltpkg/pull/642
> query: pseudo element parameter escaping

- src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
- src/graph/src/types.ts
- src/gui/src/state/load-graph.ts
- src/gui/test/components/explorer-grid/index.tsx
- src/gui/test/state/__snapshots__/load-graph.ts.snap
- src/query/src/index.ts
- src/query/src/types.ts
- src/query/test/fixtures/graph.ts
- src/security-archive/test/fixtures/graph.ts
Add a `node.toJSON` method defintion to the `QueryResponseNode`
object. This fixes properly output of insights data to stdout
when using `vlt query ...`.
graph, gui: Added a `node.toJSON` to the `NodeLike` type definition, also
updates `src/gui` to implement a proper `toJSON` and `toString`
methods for its internal `NodeLike` implementation.
> query: fix `vlt query` cli output

- src/cache-unzip/src/unzip.ts
- src/cache/src/index.ts
- src/cache/test/index.ts
Also update cache-unzip to use the reworked `cache.set` method with the
`integrity` option.
Fixes #627
> cache: handle all integrity cases when writing cache entry to disk

- src/security-archive/src/index.ts
- src/security-archive/test/index.ts
In case the xdg cache folder is missing, it should be created prior to trying to open the database.
Fixes: https://github.com/vltpkg/vltpkg/issues/670
> security-archive: fix missing cache folder

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/cli-sdk/package.json
- src/query/package.json
- src/registry-client/package.json
- src/run/package.json
- src/workspaces/package.json
Refreshes most deps except for those with known compatability
issues or breaking changes. Also skips the docs and gui workspaces
for now since those are best done in isolation.
> deps: update some prod deps

- src/query/src/index.ts
- src/query/src/pseudo.ts
- src/query/tap-snapshots/test/pseudo.ts.test.cjs
- src/query/test/index.ts
- src/query/test/pseudo.ts
When in loose mode, unknown pseudo selectors names will now fail to match any item. Using multiple selectors in the root query, e.g: `#a, #b, #c` will now switch loose mode on by default to the remainder of the query parser.
This makes it so that if the user has an unidentified pseudo selector in a multiple-selector query, e.g: `#a, :foo` they will still get a result with items matching `#a` while `:foo` is ignored.
> query: fix unmatching pseudo selectors

- src/gui/src/app/explorer.tsx
- src/gui/test/app/__snapshots__/explorer.tsx.snap
- src/gui/test/app/explorer.tsx
When a `Query.search` has an error the GUI should show no results.
This changes the current behavior of showing previous results that can be misleading to the user and make sure the results are always directly related to the current query.
https://github.com/user-attachments/assets/3f2ec63f-52f2-47b7-bc99-9baff2935276
Refs: https://github.com/vltpkg/vltpkg/issues/539
Refs: https://github.com/vltpkg/vltpkg/pull/689
> gui: clear results when search fails

- src/gui/src/state/index.ts
- src/gui/src/state/types.ts
This is an unused property that dates back to the initial proof of concept implementation.
> gui: remove state refs to selected node

- infra/smoke-test/test/gui.ts
This reverts the test added in ca7432b1242f70de60f1217c70efca34236bcd5c to a `t.skip` for now.
> smoke-test: skip gui test

- src/query/src/pseudo.ts
- src/query/tap-snapshots/test/pseudo.ts.test.cjs
- src/query/test/index.ts
- src/query/test/pseudo.ts
Tweaks the `:project` pseudo selector so that it now behaves similar to other selectors as a filter instead of always returning all importer nodes no matter what.
This will fix problems in which the selector would not work properly if not used as the first element,e.g:
vlt query '#a:project'
vs
vlt query ':project#a'
With this refactor both examples above will always return the same values.
> query: refactor project selector

- src/query/src/pseudo/outdated.ts
- src/query/tap-snapshots/test/pseudo/outdated.ts.test.cjs
- src/query/test/pseudo/outdated.ts
Fixes using the `:outdated` as a pseudo element with no params. e.g:
vlt query ':root > *:outdated'
Fixes: https://github.com/vltpkg/statusboard/issues/124
> query: fix outdated selector

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/report-test-failures.js
- src/cli-sdk/package.json
- src/cli-sdk/src/config/index.ts
- src/cli-sdk/src/exec-command.ts
- src/cli-sdk/src/output.ts
- src/cli-sdk/src/view.ts
- src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/query.ts
- src/cli-sdk/test/config/index.ts
- src/cli-sdk/test/output.ts
- src/graph/package.json
- src/graph/src/visualization/human-readable-output.ts
- src/graph/tap-snapshots/test/visualization/human-readable-output.ts.test.cjs
- src/graph/test/visualization/human-readable-output.ts
The reason for this change is not necessarily replacing `chalk` with `util.styleText`, but instead to decouple checking color support with the writing of ansi color sequences.
With this change we now detect whether both `stderr` and `stdout` should be colorized. And `ViewOptions` now only contains a `colors` boolean indicating support for `stdout` since we assume that our views will be writing to `stdout` primarily.
As a result, producers of colorized output (eg `graph`) can now use any color library without worrying about detecting support since that is all done in `output.ts`.
There is one `TODO` left which is that `output` exports mutable `styleText` functions. Those are only used by `exec` and will be cleaned up as part of #684.
> cli-sdk: use util.styleText over chalk

- src/cli-sdk/src/commands/pkg.ts
- src/cli-sdk/src/output.ts
- src/cli-sdk/tap-snapshots/test/commands/pkg.ts.test.cjs
- src/cli-sdk/test/commands/pkg.ts
Closes #490
This also makes `pkg` with the explicit flag `--view=json` work as expected. Previously only `vlt pkg get | some-other-command` would output JSON because it would detect that the output stream is not a TTY.
> cli-sdk(pkg): strip symbol keys from human output

- src/cli-sdk/src/commands/list.ts
- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
Fixes up references to no longer supported class selectors and added an intro to the query language making a reference to the Dependency Selector Syntax name.
> cli-sdk: update list & query cmd help

- src/cli-sdk/src/print-err.ts
- src/cli-sdk/tap-snapshots/test/print-err.ts.test.cjs
- src/cli-sdk/test/print-err.ts
- src/error-cause/src/index.ts
- src/registry-client/src/index.ts
**Before**
```sh
╰❯ vlt i react --registry=https://thisdoesnotexistttttttttttttttttttttt.com
build⠋ > actual > reify
1 requests
Error: getaddrinfo ENOTFOUND thisdoesnotexistttttttttttttttttttttt.com
Stack:
at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
at __node_internal_ (ext:deno_node/internal/errors.ts:246:10)
at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:43:26)
at ext:deno_node/internal_binding/cares_wrap.ts:82:9
at eventLoopTick (ext:core/01_core.js:178:7)
```
**After**
```sh
╰❯ ~/projects/vltpkg/vltpkg/scripts/bins/compile/vlt i react --registry=https://thisdoesnotexistttttttttttttttttttttt.com
build⠋ > actual > reify
1 requests
Request Error: Request failed
Code: ENOTFOUND
Syscall: getaddrinfo
URL: …
```
> cli-sdk: better error info for failed requests

- src/gui/src/lib/external-info.ts
If a package is not identified as being a registry package that is coming from the public registry, then do not try to make calls to the public registry to retrieve information about it.
> gui: fix non public registry api calls

- src/gui/src/components/explorer-grid/index.tsx
We got user feedback that labelling dependencies as "prod" is confusing since that's not a jargon end-users are used with.
Let's stop printing prod labels and only signal `dev`, `peer`, `optional` and `workspace` as labels / categories.
<table width="100%" border="0" cellspacing="0" cellpadding="10">
<tr>
<td width="50%">
</td>
<td width="50%">
</td>
</tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
<tr>
<td width="50%">
</td>
<td width="50%">
</td>
</tr>
</table>
> gui: do not use prod labels

- src/rollback-remove/src/index.ts
- src/rollback-remove/src/remove.ts
- src/rollback-remove/test/remove.ts
Fixes #707
The remover in `rollback-remove` had a bug where the child process did not properly handle stdin being empty. So if no data was ever written to the stream, it ended up parsing that as `[""]`. This result was then passed to `rimraf` which then deleted the current working directory (aka the entire project).
This case was already handled in the parent which is why we didn't catch this behavior previously. Before ever spawning the process we check if we have entries to rollback.
**BUT**
When we end up in an error state (like in #707) we explicitly call `process.exit()` because it speeds up the exiting of the CLI process (ref #449). In our published binaries we use Deno which will kill detached child processes if `process.exit()` is called directly. In that case the remover abruptly …
> rollback-remove: remove empty entries from rollback

- src/workspaces/src/index.ts
- src/workspaces/test/index.ts
Different workspaces should not share the same name.
Fixes: https://github.com/vltpkg/vltpkg/issues/358
> workspaces: fix duplicated names

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/smoke-test.yml
The release PR should always be green because we test our PRs before merging which should also be green. And then merging the release PR should always successfully publish the packages.
But these "always" things can fail for some of the following reasons. This adds slack notifications for these cases to a new slack channel `#github-alerts`. A slack app and webhook URL has already been created and added to this repo as a secret.
We've mostly squashed these for now but we want to be alerted if they start to happen again. Currently if these do happen they are easy to ignore because the PR will be recreated pretty often.
We tried turning on a rule for this on PRs but it slowed us down a lot. I think this is still the right choice but because of the nature of a monorepo with many workspaces, …
> release: notify slack from workflow for important alerts

- src/cli-sdk/src/commands/config.ts
- src/cli-sdk/src/print-err.ts
- src/cli-sdk/tap-snapshots/test/print-err.ts.test.cjs
- src/cli-sdk/test/commands/config.ts
- src/cli-sdk/test/print-err.ts
- src/error-cause/src/index.ts
Fixes #391
**Before**
```
╰❯ vlt config set registryyyyyy=https://whoa.com --config=project
Error: Unknown option '--registryyyyyy'. To specify a positional argument starting with a '-', place it at the end of the command after '--', as in '-- --registryyyyyy'
Cause:
code: JACKSPEAK
found: --registryyyyyy=https://whoa.com
Stack:
at Jack.parseRaw (/Users/lukekarrys/.config/packages/node_modules/.pnpm/jackspeak@4.1.0/node_modules/jackspeak/src/index.ts:737:17)
at set (/Users/lukekarrys/.config/packages/src/cli-sdk/src/commands/config.ts:192:17)
at command (/Users/lukekarrys/.config/packages/src/cli-sdk/src/commands/config.ts:71:14)
at outputCommand (/Users/lukekarrys/.config/packages/src/cli-sdk/src/output.ts:157:39)
at Module.run (/Users/lukekarrys/.config/packages/src/cli-sdk/src/index.ts: …
```
> cli-sdk(config): better error message when setting unknown config

- .github/workflows/ci.yml
- .github/workflows/smoke-test.yml
GUI tests fail on Node 24. This is not an issue for the actual GUI
but with the tooling required to run the tests in Node (vitest, etc).
Found a similar report here: https://github.com/reduxjs/redux-toolkit/issues/4966
For now just exclude it from the matrix always, we'll add it back later once
tooling catches up.
> ci: exclude node 24 for now [ci full-matrix]

- src/cli-sdk/src/commands/config.ts
- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/src/config/index.ts
- src/cli-sdk/src/index.ts
- src/cli-sdk/src/print-err.ts
- src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/index.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/print-err.ts.test.cjs
- src/cli-sdk/test/commands/config.ts
- src/cli-sdk/test/config/definition.ts
- src/cli-sdk/test/config/index.ts
- src/cli-sdk/test/index.ts
- src/cli-sdk/test/print-err.ts
This applies the same `code: 'ECONFIG'` behavior for all config options, including invalid values, providing more assistance beyond just listing the available options.
Now it properly detects for example when an option is given a value that shouldn't be (because it's a flag) or vice versa (not given a value to an option that is not a boolean flag), or given an invalid value (eg, `--config=asdfasdf` where only specific values are allowed).
It also properly differentiates between config _file_ errors and cli option errors, presenting the suggestions in a more useful manner.
> cli: improve how invalid options are reported

- src/query/src/pseudo.ts
- src/query/src/pseudo/root.ts
- src/query/tap-snapshots/test/pseudo/root.ts.test.cjs
- src/query/test/pseudo/root.ts
Refactor `:root` into its own file and add unit tests for it.
> query: refactor root pseudo selector

- src/query/src/pseudo.ts
- src/query/src/pseudo/type.ts
- src/query/tap-snapshots/test/pseudo/type.ts.test.cjs
- src/query/test/pseudo/type.ts
Refactor `:type(<type>)` into its own file and add unit tests for it.
> query: refactor type pseudo selector

- src/query/src/pseudo/workspace.ts
- src/query/tap-snapshots/test/pseudo/workspace.ts.test.cjs
- src/query/test/pseudo/workspace.ts
The `:workspace` selector should filter out all edges, so that it really only selects the workspace nodes and not any of its edges.
Refs: https://github.com/vltpkg/statusboard/issues/133
> query: fix workspace selector

- src/vlx/src/infer-default-executable.ts
- src/vlx/test/infer-default-executable.ts
> vlx: infer default executable when there is only one

- src/query/src/attribute.ts
- src/query/tap-snapshots/test/attribute.ts.test.cjs
After the previous id selector refactor it has been stablished that in order to provide a more concise and unambiguous experience the id selectors are the only way to select by edge name and the attribute selector should now only match in properties from the node manifest.
Based on that this changeset removes the affordance to match edge names in the attribute selector.
Refs: https://github.com/vltpkg/vltpkg/pull/643
> query: fix names in attribute selector

- www/docs/src/components/footer/theme-switcher.tsx
- www/docs/src/components/theme-provider/theme-provider.astro
Fixes vltpkg/statusboard#131
- fix theme provider to properly handle missing theme cookie by defaulting to 'system+dark'
- fix theme switcher component to default to 'system' when no theme cookie exists
- ensure consistent theme handling to prevent undefined states
> bugfix: docs theme switcher

- src/graph/tap-snapshots/test/lockfile/save.ts.test.cjs
- src/spec/src/browser.ts
- src/spec/tap-snapshots/test/browser.ts.test.cjs
- src/spec/test/browser.ts
That is, `@a/b@jsr:1.x` should be the same as `@a/b@jsr:@a/b@1.x`.
> fix: Handle jsr: without a name like yarn, pnpm do

- src/graph/src/reify/calculate-save-value.ts
- src/graph/src/reify/update-importers-package-json.ts
- src/graph/test/reify/calculate-save-value.ts
This fixes a few overlooked issues in how we save dependencies back to package.json. The new logic is, in a nutshell:
- If the user provided a specific version or range in the installation, we save that back to package.json
- If the package.json specified a specific single version, then we save that (ie, keep it pinned).
- If the final registry alias or jsr specifier did not include a version, and the package.json _does_ include a version or range, leave it un-touched, because we were just installing what the package.json said to, and it remains the authority.
- If the final registry alias or jsr specifier did not include a version range, and the package.json does not include a version or range, then we use the `^{resulting version}` range.
Fix: #638
Fix: VLT-344
> reify: save properly back to package.json

- src/query/src/index.ts
- src/query/src/types.ts
- src/query/test/index.ts
Adds a new `Query.getBreadcrumbItems` method that returns a helper object to interactively navigate a given "breadcrumb".
The "breadcrumb" is a subset of the query language that only takes root/workspaces selectors along with id selectors and combinators, allowing for usage of queries that look like a breadcrumb UI, e.g:
:root > #foo > #bar > #baz
Refs: https://github.com/vltpkg/vltpkg/issues/663
Refs: https://github.com/vltpkg/statusboard/issues/133
> query: add breadcrumb parser

- src/query/README.md
- docs were outdated
- this updates the "Examples" to show minimum reproduction cases for virtual/actual/lockfile graph querying
- afaict, this is the minimum code required for each scenario (pretty significant composition/overhead)
- please let me know if there's a way to get leaner examples
> chore(docs): update query examples

- src/graph/src/graph.ts
- src/graph/test/graph.ts
Replacing existing edges was resulting in missing nodes in the graph since the `removeNodes` method removes any edges going into the node that is about to be removed.
A straightforward and resilient solution is to make sure we remove any edge that is about to have its destination replaced from the `edgesIn` set in that original destination node.
> graph: fix edge replacement

- src/graph/src/ideal/get-importer-specs.ts
- src/package-info/src/index.ts
- src/spec/src/browser.ts
- src/spec/test/browser.ts
This fixes a few bugs that were preventing catalog support from functioning properly, as well as creating an explicit link to `astro` in the top level importer to address the occult dependency from `starlight-links-validator`.
> dogfood catalog bugfix

- src/dss-breadcrumb/README.md
- src/dss-breadcrumb/src/index.ts
- src/dss-breadcrumb/src/types.ts
- src/dss-breadcrumb/test/index.ts
Refactored the breadcrumb module to better manage state and the parsed result.
The exported class that represents the parsed result of a query is now named `Breadcrumb`, instances of this class now have a `interactive()` method that returns an `InteractiveBreadcrumb` which is now the object that is going to hold state on the current item and implements a `next()` method that allows for updating that state.
> dss-breadcrumb: interactive refactor

- src/gui/src/components/explorer-grid/results/index.tsx
- src/gui/src/components/explorer-grid/results/result-item.tsx
- src/gui/src/components/explorer-grid/selected-item/item-header.tsx
- src/gui/src/components/navigation/header.tsx
- src/gui/src/lib/constants/index.ts
- src/gui/src/lib/constants/licenses.ts
- src/gui/tailwind.config.ts
- src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/results/__snapshots__/result-item.tsx.snap
- src/gui/test/components/navigation/__snapshots__/header.tsx.snap
| Desktop | Mobile |
| --- | --- |
| <img width="500" alt="Screenshot 2025-06-03 at 12 14 48" src="https://github.com/user-attachments/assets/54c4454b-6e98-4583-9a81-d525962fd412" /> | <img width="500" alt="Screenshot 2025-06-03 at 11 59 25" src="https://github.com/user-attachments/assets/bdb8c8ae-28c3-4025-8dd0-c7d16b176d82" /> |
Continues on the `result-item` component for the gui search results view.
This PR condenses the cards from a '2-tier' card into a single card with a more compact layout,
and updates some classes to improve the cards on smaller viewports.
**updates** `header` style on mobile
**moves** `LICENSE_TYPES` into `@/lib/constants`
**updates** `result-item` style
> gui: result item condensed style

- src/vlx/src/infer-name.ts
- src/vlx/src/install.ts
- src/vlx/test/infer-name.ts
> vlx: infer a reasonable name from nameless spec

- pnpm-lock.yaml
- src/graph/package.json
- src/graph/src/index.ts
- src/graph/src/modifiers.ts
- src/graph/test/modifiers.ts
Add the module that is responsible for loading and applying user-defined "modifiers" loaded from a vlt.json file into a graph at traversal time.
Instances of `GraphModifier` class can be used as a helper to modify the graph during the graph build ideal traversal time. e.g:
```ts
const modifier = new GraphModifier(options)
modifier.load(options)
// The `tryImporter` method can be used to register the initial
// importer node along with any modifier that includes an importer
// selector, e.g:
modifier.tryImporter(graph.mainImporter)
// When traversing the graph, use the `tryNewDependency` method to
// check if a given dependency name to the current traversed node
// has matching registered modifiers, e.g:
const entries = modifier.tryNewDependency(fromNode, depName)
// Use …
```
> graph: add graph modifiers module

- src/gui/src/app/explorer.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/add-dependency.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/filter.tsx
- src/gui/src/components/ui/sidebar.tsx
- src/gui/src/components/ui/tooltip.tsx
- src/gui/test/app/__snapshots__/explorer.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/__snapshots__/filter.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/add-dependency.tsx
- src/gui/test/components/explorer-grid/dependency-sidebar/filter.tsx
| Before | After |
| --- | --- |
| <img width="100%" alt="Screenshot 2025-06-04 at 10 59 18" src="https://github.com/user-attachments/assets/23204ddb-8c46-4faf-8c63-eb1c03b097b6" /> | <img width="100%" alt="Screenshot 2025-06-04 at 12 54 19" src="https://github.com/user-attachments/assets/0dc42eec-484e-40bc-944f-a11bee4c21ba" /> |
This PR fixes the issue with the `sidebar`'s link tooltips incorrectly being rendered on the `explorer` view.
When we updated the `query-bar` component to have an absolute position in order to stick to the top of the screen when scrolling, the z-indexes collided with tooltips in the gui which were rendered on the `explorer` view.
Exported a primitive `TooltipPortal` from `Radix` in `tooltip.tsx` and wrapped the `TooltipContent` with it. This allows the content …
> gui: bugfix tooltip content overlay

- src/gui/src/app/explorer.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/add-dependency.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/context.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/empty-state.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/filter.tsx
- src/gui/src/components/explorer-grid/dependency-sidebar/index.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/test/app/__snapshots__/explorer.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/__snapshots__/empty-state.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/__snapshots__/filter.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/empty-state.tsx
- src/gui/test/components/explorer-grid/dependency-sidebar/filter.tsx
- src/gui/test/components/explorer-grid/dependency-sidebar/index.tsx
https://github.com/user-attachments/assets/ccaec0b1-004f-421c-9c93-91cc097fab29
This PR introduces new empty states for the dependency sidebar when there are no dependencies present, and an empty state for when filters are applied but no results are found.
- simplifies the animation logic for the `add-dependency`'s trigger
- bugfixes the `number-flow` on the `dependency-sidebar` header when adding new dependencies
- changes the `filteredDependencies` default to `dependencies` instead of an empty array to avoid the empty state flashing
> gui: dependency sidebar empty states

- src/dss-breadcrumb/src/index.ts
- src/dss-breadcrumb/src/types.ts
- src/dss-breadcrumb/test/index.ts
Add tracking of `specificity` data to `Breadcrumb` instances and a new helper method `specificitySort` to the module that helps with defining which query should take precedence over others.
> dss-breadcrumb: add specificity and sort

- src/dep-id/src/index.ts
- src/dep-id/tap-snapshots/test/index.ts.test.cjs
- src/dep-id/test/index.ts
Encode should happen only during at `joinDepIDTuple` time and not on `getTuple`. This was causing DepIDs generated with `getId` to be double encoded.
Fixes the issue and update the test fixtures and snapshots to use characters that actually need escaping.
> dep-id: fix double encoding in get id

- src/pick-manifest/src/index.ts
- src/pick-manifest/test/index.ts
When handling modifiers `@vltpkg/pick-manifest` gets confused about the object type being handled to it. This fixes the issue by using the more explicit type guard helper methods for both types.
> pick-manifest: fix specs vs ranges confusion

- src/gui/src/components/explorer-grid/save-query.tsx
This was caused by effect deps added during e4ecea1. Removing the dep is a stop-gap
and there should be a more React-ish way of fixing this, but I couldn't figure it out
> gui: fix infinite loop when closing save queries popover

- src/dss-breadcrumb/src/index.ts
- src/dss-breadcrumb/src/types.ts
- src/dss-breadcrumb/test/index.ts
`ModifierBreadcrumbItem` objects will now expose a `comparator()` method that will allow for checking extra values, enabling the usage of a more diverse set of pseudo selectors.
This implements the initial `:semver` and its shortcut `:v` to allow for fine tuning breadcrumb matching based on the versions of packages and user defined semver values, e.g:
:root > #eslint > #minimatch:v(3)
Refs: https://github.com/vltpkg/statusboard/issues/176
> dss-breadcrumb: add support to  `:semver` & `:v` selectors 

- src/semver/README.md
- src/semver/src/index.ts
- src/semver/test/index.ts
Add an `intersects` method that return true if there is any overlapping between two different compared `Range` objects.
import { intersects } from '@vltpkg/semver'
intersects('^1.0.0', '~1.1.1') // true
intersects('1', '2.x.x') // false
intersects('*', '3.1.1') // true
Refs: https://github.com/vltpkg/statusboard/issues/176
> semver: add intersects method

- src/dss-breadcrumb/src/index.ts
- src/dss-breadcrumb/src/types.ts
- src/dss-breadcrumb/test/index.ts
`:semver` pseudo selector should use the `@vltpkg/semver.intersects` method instead of `satisfies` in order to make it possible to compare values to dependency specs ranges.
Refs: https://github.com/vltpkg/statusboard/issues/176
> dss-breadcrumb: refactor semver comparator

- src/graph/src/ideal/check-nodes.ts
- src/graph/src/modifiers.ts
- src/graph/test/ideal/check-nodes.ts
- src/graph/test/modifiers.ts
The Dependency Selector Syntax queries used in graph modifiers may now use the `:semver()` or `:v()` selectors.
Fixes: https://github.com/vltpkg/statusboard/issues/176
> graph: add semver selector to modifiers

- src/package-info/src/index.ts
- src/package-info/test/index.ts
- src/types/src/index.ts
- src/types/test/index.ts
PR normalizes funding information for manifests, ensuring consistency (ie. `funding` should always be an array of objects). Notably, the `rawManifest` remains untouched. Querying using funding values should now be more consistent/reliable. We'll likely want to do more of this in the future (maybe even write _the_ "package.json spec") but for now this is a good start/required for @ejkorol's UI additions to display aggregate funding information.
```bash
$ vlt query '[funding]' --view=json | jq '.[] | .to.manifest.funding'
$ vlt query ':attr(funding,[type=github])' --view=json | jq '.[] | .to.manifest.funding'
$ vlt query ':attr(funding,[url*="github.com/sponsors/ljharb"])' --view=json | jq '.[] | .to.manifest.funding'
```
> fix: normalize `funding` information in managed "manifests"

- src/gui/src/components/explorer-grid/selected-item/context.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-dependencies/index.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-dependencies/tabs-funding.tsx
- src/gui/test/components/explorer-grid/selected-item/item-header.tsx
- src/gui/test/components/explorer-grid/selected-item/item.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/__snapshots__/tabs-funding.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/index.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/tabs-funding.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/tabs-insights.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/tabs-licenses.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-insight.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-manifest.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-overview.tsx
- src/gui/test/components/explorer-grid/selected-item/tabs-versions.tsx
This PR adds another new subtab inside of `tabs-dependencies` for funding information.
It allows you to see:
- The total packages looking for funding
- The count of the unique funding urls
- To query the dependencies for the funding attribute
> gui: dependencies funding tab

- src/graph/src/reify/update-importers-package-json.ts
- src/graph/tap-snapshots/test/reify/update-importers-package-json.ts.test.cjs
- src/graph/test/reify/update-importers-package-json.ts
Updating `package.json` was not working as expected if a dependency that comes later would be unchanged since the `manifestChanged` state would be overridden by the latest parsed value.
This changeset fixes it by properly keeping the previous internal to `update-importers-package-json.ts` `manifestChanged` state.
> graph: fix updating package.json

- src/gui/src/components/explorer-grid/selected-item/index.tsx
When clicking on a sidebar dependency item, the query should use the edge name instead of node in order to support aliased packages.
https://github.com/user-attachments/assets/f2e7980e-8aea-4be5-80ba-1ff728bb0595
> gui: fix dependency query

- src/gui/src/components/explorer-grid/label-helper.ts
- src/gui/src/components/ui/badge.tsx
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
- src/gui/test/components/explorer-grid/dependency-sidebar/__snapshots__/filter.tsx.snap
- src/gui/test/components/explorer-grid/results/__snapshots__/result-item.tsx.snap
- src/gui/test/components/ui/__snapshots__/badge.tsx.snap
Removes the transparent backgrounds in the dependency type colors.
> gui: change dep type colors

- src/gui/src/components/queries/create-query.tsx
- src/gui/test/components/queries/__snapshots__/create-query.tsx.snap
- src/gui/test/components/queries/create-query.tsx
The query tooltip for the saved category color was being cropped by the top level background.
> gui: fix create query tooltip

- src/graph/src/visualization/human-readable-output.ts
- src/graph/tap-snapshots/test/visualization/human-readable-output.ts.test.cjs
- src/graph/test/visualization/human-readable-output.ts
Added a `(overridden)` mark / notice to the human readable output for packages / edges that have been overridden by a graph modifier.
> graph: add overridden notice to human output

- src/gui/src/components/explorer-grid/results/result-item.tsx
- src/gui/src/lib/update-result-item.ts
- src/gui/test/lib/update-result-item.test.ts
Fix clicking on search results when the current query starts from a `:root` reference.
> gui: fix search result root nav

- src/gui/src/lib/update-result-item.ts
- src/gui/test/components/explorer-grid/results/result-item.tsx
- src/gui/test/lib/update-result-item.test.ts
Fixes a variety of broken cases when clicking on the result item view elements.
Also update the unit tests in order to prune any scenario that would not match the expected data structure of real graph items and add a few additional tests to check for missing scenarios.
> gui: fix result item queries

- .cursor/rules/code-validation-workflow.mdc
Add a note on avoiding creating test fixtures that leads to linting problems that can't be fixed without breaking the expectation of the fixtures.
> chore: add instruction to test validation

- src/query/src/pseudo.ts
- src/query/src/pseudo/overridden.ts
- src/query/tap-snapshots/test/pseudo/overridden.ts.test.cjs
- src/query/test/pseudo/overridden.ts
Add a new `:overridden` pseudo selector that selects only edges that have been overridden by a graph modifier along with its linked nodes.
Fixes: https://github.com/vltpkg/vltpkg/issues/912
> query: add overridden selector

- src/query/src/pseudo.ts
- src/query/src/pseudo/prerelease.ts
- src/query/tap-snapshots/test/pseudo/prerelease.ts.test.cjs
- src/query/test/pseudo/prerelease.ts
Add a new `:prerelease` selector that will only select packages that have prerelease versions.
Fixes: https://github.com/vltpkg/vltpkg/issues/910
> query: add query prerelease selector

- src/graph/src/visualization/human-readable-output.ts
- src/graph/tap-snapshots/test/visualization/human-readable-output.ts.test.cjs
- src/graph/test/visualization/human-readable-output.ts
Fixes the human output render for overridden packages when they're using aliased versions.
> graph: fix overridden pkg human output name

- .cursor/rules/code-validation-workflow.mdc
I noticed cursor did not knew it needed to install dependencies after adding a new dependency to a workspace. This note should prevent this error in the future.
> chore: add a note to install deps on cursor rules

- pnpm-lock.yaml
- src/package-json/package.json
- src/package-json/src/index.ts
- src/package-json/test/index.ts
Add a `find` method to `@vltpkg/package-json` that walks up the directory structure and returns the full path to the first found `package.json` file, returns `undefined` if a `package.json` can't be found and never looks at the home directory level or above.
> package-json: add find method

- pnpm-lock.yaml
- src/graph/package.json
- src/graph/src/install.ts
- src/graph/tap-snapshots/test/install.ts.test.cjs
- src/graph/test/install.ts
If there is no `package.json` file in the parsed project root, we proceed to `init` a new `package.json` before running install.
> graph: init package.json on install

- pnpm-lock.yaml
- src/cli-sdk/package.json
- src/cli-sdk/src/commands/init.ts
- src/cli-sdk/src/commands/pkg.ts
- src/cli-sdk/src/index.ts
- src/cli-sdk/tap-snapshots/test/commands/init.ts.test.cjs
- src/cli-sdk/test/commands/init.ts
- src/cli-sdk/test/config/index.ts
- src/vlt-json/src/index.ts
- www/docs/src/content/docs/cli/workspaces.mdx
Add the ability to start new workspaces from the cli, so that in a given project folder, the user may run:
vlt init -w packages/a
This will create the folders if missing, create a new package.json in the location defined and add references to find this new folder in the vlt.json config file.
Fixes: https://github.com/vltpkg/statusboard/issues/164
> cli-sdk: add init workspace support

- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/src/exec-command.ts
- src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/index.ts.test.cjs
- src/cli-sdk/test/commands/run.ts
As part of making queries a first-class citizen of the client we're normalizing the options names to use `--scope` for options that will operate at the importer level, setting what scope operations should run on and a new `--target` option will eventually be introduced to handle operations that will be selecting or targetting nodes and edges deep in the graph structure.
This change also clears up some of the weirdness / confusion brought up in the original implementation at:
da15cd0fb93b53519e8cee8e78cc82da0a53ad58
> cli-sdk: rename option query to scope

- src/cli-sdk/src/commands/list.ts
- src/cli-sdk/src/commands/pkg.ts
- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/pkg.ts
- src/cli-sdk/test/commands/query.ts
- src/graph/src/node.ts
- src/graph/test/node.ts
Add support to the `--scope` option to the following commands:
- `vlt pkg`
- `vlt ls`
- `vlt query`
In `vlt pkg` the `scope` option will now allow for retrieving, setting and removing keys from the `package.json` file of any packages found using the provided `scope` query.
In `vlt ls` and `vlt query` using the `scope` option allows for setting arbitrary roots for selecting a sub-graph that can then be visualized in all the supported formats.
> cli-sdk: add `--scope` to `pkg`, `ls`, `query`

- src/graph/src/ideal/append-nodes.ts
- src/graph/test/ideal/append-nodes.ts
Add support to a `"-"` `bareSpec` definition in the graph modifiers that enables removing a given edge from the graph.
Fixes: https://github.com/vltpkg/statusboard/issues/175
> graph: add edge modifier removal

- pnpm-lock.yaml
- src/gui/package.json
- src/gui/src/components/explorer-grid/index.tsx
- src/gui/src/components/explorer-grid/selected-item/item-header.tsx
- src/gui/src/components/explorer-grid/types.ts
- src/gui/src/components/navigation/crumb-nav.tsx
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/item-header.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/item-header.tsx
- src/gui/test/components/navigation/__snapshots__/crumb-nav.tsx.snap
- src/gui/test/components/navigation/crumb-nav.tsx
This PR introduces a new way of navigating the selected item's ancestry by adding a `crumb-nav` component. The `crumb-nav` is placed into the selected item's `item-header` and utilizes `@vltpkg/dss-breadcrumb` to parse the breadcrumbs from the current query in the `state` to render the trail.
This allows quick navigation to the parent items, making a nice quality of life improvement
- **feat: creates `crumb-nav` to navigate selected item ancestry**
- **feat: integrates `crumb-nav` into the `item-header`**
> gui: feat breadcrumb navigation

- src/graph/src/types.ts
- src/gui/src/components/explorer-grid/overview-sidebar/index.tsx
- src/gui/src/components/explorer-grid/selected-item/index.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/src/lib/update-dependents-item.ts
- src/gui/src/state/load-graph.ts
- src/gui/test/components/explorer-grid/overview-sidebar/__snapshots__/index.tsx.snap
- src/gui/test/lib/update-dependents-item.test.ts
Added tests to cover a variety of possible scenarios and fixes the expectation of how clicking on different types of items should work in the left-hand side of the Explore view.
Fixes: https://github.com/vltpkg/vltpkg/issues/964
> gui: fix dependents update click handler

- src/dep-id/src/browser.ts
- src/dep-id/src/index.ts
- src/dep-id/tap-snapshots/test/index.ts.test.cjs
- src/dep-id/test/index.ts
Adds a `baseDepID()` method to `@vltpkg/dep-id`.
This new method allows for comparing and recognizing modified nodes with dep-id containing extra information with just regular graph nodes.
> dep-id: add base dep id method

- src/gui/src/components/explorer-grid/index.tsx
- src/gui/src/components/explorer-grid/selected-item/index.tsx
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/index.tsx
Stacking elements and navigating dependents was not working properly when using graph modifiers due to the possibility of finding forked nodes in the graph. This fixes it by properly handling it using the base dep ids instead.
> gui: fix graph modifier navigation

- src/cli-sdk/src/commands/list.ts
- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/query.ts
Removes the check that avoids loading security insights based on whether security insight selectors were used in the query provided to either `vlt query` or `vlt ls`.
By removing that extra check, security insights data is now always loaded and available on insights when using `--view=json` output.
Fixes: https://github.com/vltpkg/vltpkg/issues/788
> cli-sdk: always load security insights info

- src/cli-sdk/src/commands/list.ts
- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/commands/query.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
- src/cli-sdk/tap-snapshots/test/index.ts.test.cjs
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/query.ts
Adds a `--target` option to the `vlt query` and `vlt ls` commands, combined with `--scope`, the `--target` option allows for retrieving and rendering a sub graph that starts at scope and contains the elements defined in the target query.
Refs: https://github.com/vltpkg/vltpkg/issues/963
> cli-sdk: add target option to `query` and `ls`

- src/gui/src/components/explorer-grid/selected-item/context.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-contributors.tsx
- src/gui/src/components/explorer-grid/selected-item/tabs-overview.tsx
- src/gui/src/lib/external-info.ts
- src/gui/src/routes.tsx
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-contributors.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-overview.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/tabs-contributors.tsx
- src/gui/test/lib/external-info.ts
- src/types/src/index.ts
The previous contributor list in the overview tab was visually distracting and chaotic, this PR resolves this issue by creating a new hidden `tabs-contributors` view within the selected item, that is accessible by clicking 'see all contributors' button, and provides a cleaner and more organized view of contributors.
Additionally, this PR aggregates the `contributors` and `maintainers` not from the `manifest` but from the `packument`
| overview tab | contributor tab |
| --- | --- |
| <img width="600px" alt="Screenshot 2025-06-28 at 03 00 29" src="https://github.com/user-attachments/assets/394bf634-3d94-46c1-88d6-43cd3a2eab14" /> | <img width="500px" alt="Screenshot 2025-06-28 at 03 00 36" src="https://github.com/user-attachments/assets/d363d58f-bf51-4784-9c5b-1615bb579d5c" /> |
- **feat: …
> gui: update contributor list

- src/server/src/graph-data.ts
- src/server/test/graph-data.ts
The GUI server now always load data from the hidden lockfile instead of loading from traversing the `node_modules` folder. This ensures it has access to the `ManifestRegistry` object that is returned from the registry which contains additional data such as `dist` and a complete set of `contributors` which is normalized from the `maintainers` data.
Refs: https://github.com/vltpkg/vltpkg/pull/977
Refs: https://github.com/vltpkg/vltpkg/pull/947
> server: load data from hidden lockfile

- CONTRIBUTING.md
I noticed we have a mention to merging the release PR using the rebase option in the PR itself in the form of the `gh` scripts to run:
```
gh pr merge -R vltpkg/vltpkg --rebase release
```
But I would like to also have a mention in the CONTRIBUTING file so that if I'm approving / merging the release PR from the GitHub web UI there's also a note on using the rebase option to keep it consistent.
> chore: note on how to merge the release pr

- src/gui/src/components/dashboard-grid/dashboard-item.tsx
- src/gui/src/components/dashboard-grid/index.tsx
- src/gui/test/components/dashboard-grid/__snapshots__/dashboard-item.tsx.snap
- src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
- src/gui/test/components/dashboard-grid/dashboard-item.tsx
- src/gui/test/components/dashboard-grid/index.tsx
This PR simplifies the `dashboard-item` card design. It moves the `dashboard-item` into a separate file and updates the icon position and style of the cards.
Closes #868 
- **feat: moves `dashboard-item` into its own component**
- **feat: simplifies dashbaord card design**
> gui: dashboard card design update

- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/src/main.css
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
| Before | After |
|---|---|
| <img width="355" height="61" alt="Screenshot 2025-07-11 at 11 56 56" src="https://github.com/user-attachments/assets/80f09df2-eac2-4dce-993c-359132e6af01" /> | <img width="355" height="61" alt="Screenshot 2025-07-11 at 11 48 29" src="https://github.com/user-attachments/assets/d7d64b01-2ef6-4799-a27e-321b282a98a7" /> |
This PR re-implements the 'stacked' look for items that contain more than one entry and relocates the 'x and more.' to a badge within `<SideItemBadges />`
> gui: update `side-item` alises

- src/gui/src/components/navigation/crumb-nav.tsx
The more complex navigation logic such as found in:
- src/gui/src/lib/update-dependents-item.ts
- src/gui/src/lib/update-result-item.ts
Assume that direct dependency queries are split using spaces in between the direct dependency comparator, e.g: ` > `
This PR modifies it so that clicking on the parent and / or dependent items still work as expected after clicking in a breadcrumb item.
> gui: fix breadcrumb links

- pnpm-lock.yaml
- src/graph/src/actual/load.ts
- src/graph/src/node.ts
- src/types/package.json
- src/types/src/index.ts
- src/types/test/index.ts
Adds a normalization step to `manifest.version` values, properly parsing
semver values and asserting they're valid.
> types: add manifest.version normalization

- src/types/src/index.ts
- src/types/test/index.ts
`normalizeVersion` should not accept empty values as `manifest.version`
> types: fix version normalization

- src/gui/src/components/explorer-grid/selected-item/tabs-versions.tsx
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-versions.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/tabs-versions.tsx
Closes #1023
- wraps the `TooltipContent` with a `TooltipPortal`
> gui: bugfix `tabs-versions` tooltip collisions

- .github/workflows/add-to-project.yml
- github hasn't added semver resolution to actions yet (most actions previously supported `v{n}`/`{n}` tags but `actions/add-to-project` doesn't seem to have that on the marketplace)
- this changes the spec to use the exact `v1.0.2` tag
> fix: actions version to be explicit

- src/gui/src/components/explorer-grid/overview-sidebar/index.tsx
- src/gui/src/components/explorer-grid/selected-item/index.tsx
- src/gui/src/components/explorer-grid/side-item.tsx
- src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
- src/gui/test/components/explorer-grid/selected-item/__snapshots__/index.tsx.snap
- src/gui/test/components/explorer-grid/side-item.tsx
This PR expands on the `side-item` by showing the `selected-item` name and `spec` under the `parent` for better context.
Resolves #1024
> gui: add `selected-item` name + spec to `side-item`

- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/src/exec-command.ts
- src/cli-sdk/src/output.ts
- src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/query.ts
- src/cli-sdk/test/config/definition.ts
- src/cli-sdk/test/output.ts
While working in our benchmarking suite:
https://github.com/vltpkg/benchmarks/
I noticed that vlt is the only cli that did not implemented a silent install option.
This changeset adds a new `silent` view option that supresses all output to the terminal to all commands that support the `view` option.
> cli-sdk: add a `--view=silent` option

- .cursor/rules/graph/lockfiles.mdc
- .cursor/rules/monorepo-structure.mdc
Add a cursor rule with more information and context on how the lockfile system works internal to the vlt client.
> chore: add lockfile cursor rules

- .github/workflows/vlt.yml
- src/cli-sdk/src/config/definition.ts
- src/cli-sdk/test/config/definition.ts
- src/cli-sdk/test/output.ts
This preserves the behavior of the view being inferred as JSON when
piping between commands, except when that is done in a CI environment.
> fix(cli-sdk): output human views in CI

- infra/cli-benchmarks/scripts/variations/cache-lockfile-node-modules.sh
- infra/cli-benchmarks/scripts/variations/cache-lockfile.sh
- infra/cli-benchmarks/scripts/variations/clean.sh
- infra/cli-benchmarks/scripts/variations/common.sh
- infra/cli-benchmarks/scripts/variations/lockfile.sh
This has no effect on CI benchmarks but now the `vlt` binary is supplied to hyperfine via `--parameter-list`. This allows for locally running the benchmarks against a baseline to help debug performance.
Here's how I'm using it locally with two local copies of the `vltpkg/vltpkg` repo:
```sh
export BENCH_BINARY="$(pwd)/scripts/bins/bundle/vlt,/Users/lukekarrys/projects/vltpkg/vltpkg-clean/scripts/bins/bundle/vlt"
bash ./infra/cli-benchmarks/scripts/benchmark.sh abbrev clean
```
> chore(benchmark): set binary through hyperfine parameter list

- .cursor/rules/graph/data-structure.mdc
- .cursor/rules/graph/ideal.mdc
- .cursor/rules/graph/index.mdc
- .cursor/rules/graph/load-actual.mdc
- .cursor/rules/graph/lockfiles.mdc
- .cursor/rules/graph/modifiers.mdc
- .cursor/rules/graph/reify.mdc
- .cursor/rules/monorepo-structure.mdc
- src/graph/README.md
Adds various cursor rule that provides an overview of how to effectively work with the `@vltpkg/graph` library and expanded user documentation in `src/graph/README.md`.
Refs: https://github.com/vltpkg/vltpkg/issues/748
> graph: document graph library

- src/query/src/pseudo.ts
- src/query/src/pseudo/spec.ts
- src/query/tap-snapshots/test/pseudo/spec.ts.test.cjs
- src/query/test/pseudo/spec.ts
- www/docs/src/content/docs/cli/selectors.mdx
Adds a new `:spec` selector that allows for selecting packages based on the package specifier argument used by its dependent, e.g:
Package `@vltpkg/a` has the following manifest:
```
{
"name": "@vltpkg/a",
"dependencies": {
"@vltpkg/b": "^1.0.0"
}
}
```
It's then possible to select `@vltpkg/b` using:
```
:spec(^1.0.0)
```
Fixes: https://github.com/vltpkg/vltpkg/issues/1092
> query: add spec pseudo selector

- src/dep-id/src/browser.ts
- src/graph/src/actual/load.ts
- src/graph/src/graph.ts
- src/graph/src/ideal/build-ideal-from-starting-graph.ts
- src/graph/src/lockfile/load-edges.ts
- src/graph/tap-snapshots/test/graph.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/append-nodes.ts.test.cjs
- src/graph/tap-snapshots/test/ideal/build-ideal-from-starting-graph.ts.test.cjs
- src/graph/test/graph.ts
- src/graph/test/ideal/append-nodes.ts
- src/graph/test/ideal/build-ideal-from-starting-graph.ts
- src/gui/src/state/load-graph.ts
- src/spec/src/browser.ts
- src/spec/src/types.ts
- src/spec/test/browser.ts
Various fixes to the graph library and some of its auxiliary libraries with the goal of insuring installs are deterministic.
- Added an inheritedRegistry setter to the `Spec` object.
- Added references to the inherited registry to nodes being loaded from the actual file.
- Fixed `@vltpkg/dep-id` hydration, adding missing spec options forwarding and always referencing a name.
- Added the ability to hydrate the resolution cache with nodes loaded from a lockfile
Refs: https://github.com/vltpkg/vltpkg/issues/748
> graph: fix various graph issues

- src/graph/src/ideal/append-nodes.ts
- src/graph/test/ideal/append-nodes.ts
Refactors the append nodes step of building an ideal graph so that the manifest fetching logic is split from the graph-building logic, allowing for concurrently retrieving manifest data while adding determinism to the graph building order.
Refs: https://github.com/vltpkg/vltpkg/issues/748
Refs: https://github.com/vltpkg/vltpkg/pull/1094
> graph: deterministic append nodes

- infra/smoke-test/test/install.ts
- src/cli-sdk/src/commands/install/reporter.ts
This allows us to not use waitUntilExit() which for some reason results in
the process exiting with a 13 status code.
Fixes: https://github.com/vltpkg/vltpkg/issues/1123
> fix(cli-sdk): render elapsed install time as part of ink output

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/cli-sdk/package.json
- src/gui/tsconfig.json
- www/docs/tsconfig.json
This is preferable to the `tsconfig` settings that were set previously, because it works better with editor linting as well.
> chore: correct react versions in workspaces with pnpm overrides

- src/vlt-json/src/index.ts
- src/vlt-json/test/index.ts
`vlt config set ... --config=user` silently fails today if the `vlt.json` doesn't exists as it's not able to create it in the path (because the `vlt` dir also doesn't exist in the path to the user-level config).
> fix: create path for user level config if it doesnt exist

- src/error-cause/src/index.ts
- src/registry-client/src/cache-entry.ts
- src/registry-client/src/handle-304-response.ts
- src/registry-client/src/index.ts
- src/registry-client/src/raw-header.ts
- src/registry-client/src/redirect.ts
- src/registry-client/src/set-raw-header.ts
- src/registry-client/src/string-encoding.ts
- src/registry-client/test/cache-entry.ts
- src/registry-client/test/fixtures/to-raw-headers.ts
- src/registry-client/test/index.ts
- src/registry-client/test/raw-header.ts
- src/registry-client/test/set-raw-header.ts
- Normalizes usage of lower level `Uint8Array` objects
- Avoids unnecessary memory copies
- Uses fixed-size buffers when `content-length` is known
Refs: https://github.com/vltpkg/vltpkg/issues/1088
> registry-client: memory management cleanup

- src/registry-client/src/string-encoding.ts
- src/registry-client/test/cache-entry.ts
- src/registry-client/test/fixtures/to-raw-headers.ts
- src/registry-client/test/raw-header.ts
- src/registry-client/test/set-raw-header.ts
`Buffer.from` is faster for encoding strings.
Refs: https://github.com/vltpkg/vltpkg/issues/1088
> registry-client: encode strings using buffer from

- www/docs/src/components/sidebar/data.tsx
- www/docs/src/components/sidebar/sidebar-sublist.tsx
- www/docs/src/components/sidebar/sidebar.tsx
| Before | After |
| --- | --- |
| <img width="285" height="769" alt="Screenshot 2025-09-09 at 12 58 29" src="https://github.com/user-attachments/assets/3d9fb4ec-0a5c-41fd-ba7f-a26c99ae2370" /> | <img width="285" height="668" alt="Screenshot 2025-09-09 at 12 55 39" src="https://github.com/user-attachments/assets/3b31f467-f8bb-4502-b338-c39961b38852" /> |
This PR updates the docs sidebar so that top level navigation on the sidebar is no longer collapsible, and icons only appear when the depth level is 0.
However this also preserves the `internals` package icons on the sidebar, where those are collapisble sections.
- creates `SidebarSection` component to wrap the top level segments
- removes icons from the titles
- moves icons to depth 0 (top level routes)
- maintains package icons in …
> docs: update sidebar icon format

- src/server/src/dashboard.ts
- src/server/src/get-readable-path.ts
- src/server/src/index.ts
- src/server/src/listen-carefully.ts
- src/server/src/read-project-folders.ts
- src/server/test/dashboard.ts
- src/server/test/get-readable-path.ts
- src/server/test/read-project-folders.ts
- modified the host/port config to accommodate codespace envs where the logged url is wrong/stuck on `localhost` & `dashboard.json` fails to load
- added graceful fallback for `homedir()` if it throws (rare but can happen)
> fix(server): port forwarding/dashboard loading in codespace envs

- src/cli-sdk/src/commands/list.ts
- src/cli-sdk/src/commands/query.ts
- src/cli-sdk/src/query-host-contexts.ts
- src/cli-sdk/test/commands/list.ts
- src/cli-sdk/test/commands/query.ts
- src/gui/src/components/query-builder/options.ts
- src/gui/src/lib/constants/selectors.ts
- src/gui/src/lib/query-host-contexts.ts
- src/gui/src/lib/update-dependents-item.ts
- src/gui/src/lib/update-result-item.ts
- src/query/src/pseudo.ts
- src/query/src/pseudo/host.ts
- src/query/test/pseudo/host-context.ts
- www/docs/src/content/docs/cli/security.mdx
- www/docs/src/content/docs/cli/selectors.mdx
The previously named `:host-context` query selector is now named `:host`.
> chore: rename host-context selector

- src/graph/src/actual/load.ts
The load hidden lockfile method within `actual.load()` was missing proper options forwarding, this was causing the security archive to not properly hydrate data.
> graph: fix load hidden lockfile options

- src/graph/src/virtual-root.ts
- src/gui/src/lib/query-host-contexts.ts
- src/query/src/types.ts
- src/server/src/handle-request.ts
Fixes security archive data integration with actual loaded data and transfering to the GUI, particularly when using the `:host()` selector.
> gui: fix security-archive integration
