vltpkg/vltpkg

.github/workflows/publish-workspaces.yml
infra/benchmark/package.json
package.json
scripts/check-deps.js
scripts/consistent-package-json.js
scripts/make-dist-bins.js
scripts/publish-workspaces.js
scripts/update-deps.js
scripts/utils.js
src/cache-unzip/package.json
src/vlt/package.json

publish: move workspace preinstall script to root only

---

www/docs/astro.config.mts

docs: copy pagefind files

---

www/docs/src/components/header/linear-menu.tsx

www/docs/src/components/header/linear-menu.tsx
```diff
-     { title: 'Blog', path: '/' },
+     { title: 'Blog', path: 'https://blog.vlt.sh/' },
```

docs: fixed link to blog

---

src/gui/src/app/error-found.tsx
src/gui/src/state/index.ts
src/gui/src/state/types.ts

updates the error view's back button to correctly route to the previous state
- adds previousRoute to state
- update error-found view button

error back button bug

---

src/vlt/src/start-gui.ts

Refs: https://github.com/vltpkg/vltpkg/issues/329

gui: short dashboard homedir paths

---

src/gui/src/components/explorer-grid/dependency-side-bar.tsx
src/gui/src/components/explorer-grid/save-query.tsx
src/gui/src/components/ui/popover.tsx
src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
src/gui/test/components/explorer-grid/__snapshots__/save-query.tsx.snap
src/gui/test/components/ui/__snapshots__/popover.tsx.snap

Fixes conflicting z-index issues from the dependencies.
Removes nested buttons, since triggers are buttons anyways.
Disabled password autocomplete on inputs.
Updates test snapshots

gui popover bugfixes

---

src/gui/src/components/explorer-grid/index.tsx

List workspaces to the left of the root project details when selected.

gui: add root workspaces shortcut

---

src/package-info/test/index.ts

Should fix and / or help improve on the windows flaky tests first manifested / noticed on https://github.com/vltpkg/vltpkg/pull/371 tests.

package-info: fix windows flaky test

---

src/gui/src/components/explorer-grid/index.tsx

Follow up from the introduction of workspaces listing next to the project root details view.
Refs: https://github.com/vltpkg/vltpkg/pull/372

gui: fix workspaces versions

---

www/docs/astro.config.mts
www/docs/src/components/hero/hero.tsx

docs: add mixpanel

---

README.md

- cleans up readme
- adds some basic badging

chore: clean up readme & add badges

---

src/gui/src/components/explorer-grid/side-item.tsx
src/gui/test/components/explorer-grid/__snapshots__/index.tsx.snap
src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap

feat: card layout cleanup

---

src/gui/src/app/create-new-project.tsx
src/gui/src/components/create-new-project/index.tsx
src/gui/src/components/dashboard-grid/index.tsx
src/gui/src/components/explorer-grid/selected-item.tsx
src/gui/src/components/navigation/header.tsx
src/gui/src/layout.tsx
src/gui/src/state/types.ts
src/gui/test/app/__snapshots__/create-new-project.tsx.snap
src/gui/test/app/create-new-project.tsx
src/gui/test/components/create-new-project/__snapshots__/index.tsx.snap
src/gui/test/components/create-new-project/index.tsx
src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
src/gui/test/components/dashboard-grid/index.tsx

Adds a new interface that allows for creating a new project from the GUI using the same underlying system from `vlt init`.
https://github.com/user-attachments/assets/ed0b296e-305b-4ffd-b69e-ad57c5a43be8

gui: dashboard create new project

---

src/gui/src/components/dashboard-grid/dashboard-table.tsx
src/gui/src/components/dashboard-grid/index.tsx
src/gui/test/components/dashboard-grid/dashboard-table.tsx

Refactored the dashboard click handlers to make sure both the table and grid views share the same event handler.
Also adds an in-progress state that will render a spinner, in order to improve UX when loading larger project graphs.

gui: refactor dashboard click handlers

---

pnpm-lock.yaml
www/docs/package.json
www/docs/src/components/header/astro-header.astro
www/docs/src/components/header/linear-menu.tsx
www/docs/src/components/page-sidebar/mobile-sidebar.tsx
www/docs/src/components/page-sidebar/page-sidebar.tsx
www/docs/src/components/sidebar/mobile-sidebar.tsx
www/docs/src/components/two-column-layout/astro-two-column-layout.astro
www/docs/src/components/ui/drawer.tsx
www/docs/src/components/ui/scroll-area.tsx
www/docs/src/styles/globals.css

- updates `navbar` to be consistent with other platforms
- updates styles to `search` component
- updates `page-sidebar` mobile menu
- updates mobile `navbar` styling
Fixes #285 
<details>
<summary>
<h3>Mobile navbar</h3>
</summary>
<h3>Mobile page-sidebar</h3>
</details>

(DOCS) styling updates

---

src/gui/src/app/explorer.tsx

Improves the responsiveness of the UI by cancelling any ongoing query search prior to creating a new one.
Fixes: https://github.com/vltpkg/vltpkg/issues/360
Depends on: https://github.com/vltpkg/vltpkg/pull/440

gui: add ability to cancel ongoing query search

---

src/gui/src/components/explorer-grid/setup-project.tsx
src/gui/src/components/navigation/header.tsx
src/gui/src/components/ui/inline-code.tsx
src/gui/test/components/explorer-grid/__snapshots__/setup-project.tsx.snap
src/gui/test/components/explorer-grid/setup-project.tsx
src/gui/test/components/ui/__snapshots__/inline-code.tsx.snap
src/gui/test/components/ui/inline-code.tsx

Updates the styles for `Setup Project`.

gui: create new project styles

---

src/gui/src/components/dashboard-grid/index.tsx
src/gui/src/components/dashboard-grid/table-columns.tsx
src/gui/src/components/data-table/data-table.tsx
src/gui/src/components/data-table/table-filter-search.tsx
src/gui/src/components/data-table/table-view-dropdown.tsx
src/gui/src/components/sort-dropdown.tsx
src/gui/src/components/ui/filter-search.tsx
src/gui/src/components/ui/inline-code.tsx
src/gui/src/components/ui/kbd.tsx
src/gui/test/components/__snapshots__/sort-dropdown.tsx.snap
src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
src/gui/test/components/dashboard-grid/index.tsx
src/gui/test/components/sort-dropdown.tsx
src/gui/test/components/ui/__snapshots__/filter-search.tsx.snap

- **updates dashboard layout style.**
- **chore: lint**

gui: update dashboard style

---

src/gui/src/components/navigation/sidebar/logo.tsx
src/gui/test/components/navigation/sidebar/__snapshots__/logo.tsx.snap

fixes the error message on invalid dom element nesting related to the tooltips in the sidebar

gui: bugfix invalid dom nesting

---

src/gui/src/components/explorer-grid/selected-item.tsx
src/gui/src/lib/external-info.ts

Added `versions` and `greaterVersions` info to the `details` object available at the `selected-item` view.
https://github.com/user-attachments/assets/d6c69646-36a3-40dc-905a-75c7ac0558a5

gui: add outdated info to selected item details

---

CONTRIBUTING.md

This is an issue I ran into when converting our tests to use `--experimental-strip-types`. It is mostly mitigated by ensuring we separate type imports and value imports, but it can still pop up if something is imported at the top level of a test.
This PR adds a contributing FAQ section to explain how to work around the issue.

contributing: add faq about weird coverage issue

---

src/vlt/package.json

:rotating_light: Merging this PR will publish `vlt@0.0.0-1` :rotating_light:
Steps to merge:
1. [x] `gh pr review -R vltpkg/vltpkg --approve 485`
2. [x] `gh pr merge -R vltpkg/vltpkg --rebase 485`
- bundle: https://github.com/vltpkg/vltpkg/actions/runs/13557404977/artifacts/2660396548
- darwin-arm64: https://github.com/vltpkg/vltpkg/actions/runs/13557404977/artifacts/2660398775
- darwin-x64: https://github.com/vltpkg/vltpkg/actions/runs/13557404977/artifacts/2660398822
- linux-arm64: https://github.com/vltpkg/vltpkg/actions/runs/13557404977/artifacts/2660398877
- linux-x64: https://github.com/vltpkg/vltpkg/actions/runs/13557404977/artifacts/2660398919
- win32-x64: https://github.com/vltpkg/vltpkg/actions/runs/13557404977/artifacts/2660398971

Release v0.0.0-1

---

www/docs/src/content/docs/cli/using-with-vsr.mdx
www/docs/src/styles/globals.css

Add a guide showing how to use a VSR instance with the vlt client.

docs: add using with vsr guide

---

src/vlt/src/commands/uninstall.ts
src/vlt/test/commands/uninstall.ts

Closes https://github.com/vltpkg/statusboard/issues/39

uninstall: use install reporter for human view

---

src/gui/README.md

Adds documentation in the readme for how to run the esbuild dev server with live reloading
Closes vltpkg/statusboard#83

update gui README

---

src/gui/src/components/explorer-grid/selected-item.tsx
src/gui/src/components/ui/tabs.tsx
src/gui/test/components/explorer-grid/__snapshots__/selected-item.tsx.snap

Small UI update to introduce some states on the tab hover
https://github.com/user-attachments/assets/81fd1683-21fb-4242-b153-5d9532550da3
https://github.com/user-attachments/assets/386e639e-8e8f-4f0d-a990-684da0d25e70

gui: animate tab primitive

---

src/gui/src/components/navigation/sidebar/nav-project-queries.tsx
src/gui/src/components/ui/collapsible.tsx
src/gui/src/components/ui/sidebar.tsx

Adds some small micro interactions to the sidebar
- supercharges the `collapsible` primitive with `motion`
- updates `duration` properties on `sidebar` states
- updates `nav-project-queries` for list animation
https://github.com/user-attachments/assets/8cc01ebe-1416-46f6-affc-423f1a93a520
https://github.com/user-attachments/assets/3b4b1674-8406-4509-9b3c-bb25bc30b1d1

gui: animate sidebar items

---

src/gui/src/components/create-new-project/index.tsx
src/gui/src/components/directory-select.tsx
src/gui/src/components/explorer-grid/index.tsx
src/gui/src/components/explorer-grid/selected-item.tsx
src/gui/src/components/queries/saved-item.tsx
src/gui/src/lib/external-info.ts
src/gui/test/components/__snapshots__/directory-select.tsx.snap
src/gui/test/components/create-new-project/__snapshots__/index.tsx.snap
src/gui/test/lib/external-info.ts

Closes vltpkg/statusboard#95
- correctly renders `selected-item` on initial gui startup
- **bugfix**: uses the correct directories in `directory-select`
- **bugfix**: renders the correct query directory display value

[GUI] [BUGFIX] initial `selected-item` and `directory-select`

---

infra/smoke-test/test/cache-unzip.ts
pnpm-lock.yaml
src/cache/src/index.ts
src/cache/test/index.ts
src/cli-sdk/src/config/definition.ts
src/cli-sdk/tap-snapshots/test/commands/help.ts.test.cjs
src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
src/registry-client/src/cache-entry.ts
src/registry-client/src/cache-revalidate.ts
src/registry-client/src/index.ts
src/registry-client/src/revalidate.ts
src/registry-client/tap-snapshots/test/cache-entry.ts.test.cjs
src/registry-client/test/cache-entry.ts
src/registry-client/test/cache-revalidate.ts
src/registry-client/test/fixtures/to-raw-headers.ts
src/registry-client/test/index.ts
src/registry-client/test/revalidate.ts
src/security-archive/src/index.ts

This adds `stale-while-revalidate` support to the registry-client.

stale-while-revalidate

---

src/cli-sdk/src/commands/list.ts
src/cli-sdk/tap-snapshots/test/commands/list.ts.test.cjs

Fixes: https://github.com/vltpkg/vltpkg/issues/590

cli-sdk: quote example on how to list all

---

src/security-archive/src/types.ts

Fixes: https://github.com/vltpkg/vltpkg/issues/598

security-archive: fix medium severity type

---

eslint.config.mjs
src/cli-sdk/test/commands/cache.ts
src/query/test/index.ts
src/query/tsconfig.json
src/registry-client/src/index.ts

Also some cleanup for tsconfigs and removing unnecessary try/catch

lint: allow throwing unknown

---

src/gui/src/app/help/help-selectors.tsx
src/gui/src/components/help-selectors/content.ts
src/gui/src/components/help-selectors/selector-table-columns.tsx
src/gui/src/components/navigation/header.tsx
src/gui/src/lib/constants/index.ts
src/gui/src/lib/constants/selectors.ts
src/gui/src/lib/constants/socket.ts
src/gui/test/app/help/__snapshots__/help-selectors.tsx.snap
src/gui/test/components/navigation/__snapshots__/header.tsx.snap

extends on the #591 by adding all known selectors into the help page

gui: add all known selectors into help page

---

src/gui/src/components/navigation/sidebar/sidebar-menu-link.tsx
src/gui/src/components/ui/tabs.tsx

updates the transitions on the tabs to make them feel snappier

gui: update animation transitions on tabs

---

src/keychain/src/index.ts

keychain: ignore extra errors from load

---

src/gui/src/components/explorer-grid/selected-item/tabs-versions.tsx

https://github.com/user-attachments/assets/0a1760d6-a392-495c-9f89-674d42d2a50a

gui: versions tab filter animations

---

src/semver/src/range.ts
src/semver/test/fixtures/ranges.ts
src/semver/test/range.ts

Closes https://github.com/vltpkg/vltpkg/issues/273
Co-authored-by: @isaacs

semver: dont throw if ranges have at least one valid comparator

---

infra/smoke-test/test/cache-unzip.ts
infra/smoke-test/test/fixtures/run.ts
infra/smoke-test/test/install.ts
infra/smoke-test/test/rollback-remove.ts

Also use t.comment for debug logging since CI runs tests sequentially

smoke-test: add timeout option

---

.github/workflows/smoke-test.yml
infra/smoke-test/test/fixtures/run.ts
infra/smoke-test/test/gui.ts
infra/smoke-test/test/postinstall.ts

smoke-test: enable on all PRs

---

src/gui/src/components/explorer-grid/selected-item/item-header.tsx
src/gui/src/lib/external-info.ts
src/gui/test/components/explorer-grid/selected-item/__snapshots__/item-header.tsx.snap
src/gui/test/components/explorer-grid/selected-item/item-header.tsx
src/gui/test/lib/external-info.ts

appends `gitHead` to version information from packument and adds `gitHead` information next to publisher.

gui: selected item `gitHead` information

---

src/gui/src/components/explorer-grid/selected-item/item-header.tsx
src/gui/src/components/explorer-grid/selected-item/tabs-overview.tsx
src/gui/src/lib/external-info.ts
src/gui/test/components/explorer-grid/selected-item/__snapshots__/item-header.tsx.snap
src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-overview.tsx.snap
src/gui/test/components/explorer-grid/selected-item/tabs-overview.tsx
src/gui/test/lib/external-info.ts

renders the `contributors` from the `manifest` in the `tabs-overview`

gui: selected item contributors

---

knip.ts
package.json
pnpm-lock.yaml

Sorry it was hurting my eyes, just had to do this 🤷‍♂️ 😃

deps: update knip + config

---

src/gui/src/components/explorer-grid/selected-item/tabs-overview.tsx
src/gui/src/components/icons/github-outline.tsx
src/gui/src/components/icons/index.ts
src/gui/src/components/ui/link.tsx
src/gui/src/lib/external-info.ts
src/gui/src/utils/get-repo-url.ts
src/gui/src/utils/human-number.ts
src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-overview.tsx.snap
src/gui/test/components/explorer-grid/selected-item/tabs-overview.tsx
src/gui/test/components/icons/__snapshots__/github-outline.tsx.snap
src/gui/test/components/icons/__snapshots__/glyph-icon.tsx.snap
src/gui/test/components/icons/github-outline.tsx
src/gui/test/components/icons/glyph-icon.tsx
src/gui/test/components/ui/__snapshots__/link.tsx.snap
src/gui/test/components/ui/link.tsx
src/gui/test/lib/external-info.ts
src/gui/test/utils/get-repo-url.ts

- creates new style for an `aside` like view for the details of the package
- updates some styles for consistency
- shows the stars, open issue count, open pr count and repository information on the package

gui: selected-item  stars, issue and pr count

---

src/query/test/fixtures/graph.ts
src/query/test/pseudo/semver.ts
src/security-archive/test/fixtures/graph.ts

These notes are no longer true and this TODO is just a leftover from implementation.

chore: remove outdated comments

---

src/gui/src/components/explorer-grid/selected-item/tabs-manifest.tsx
src/gui/src/components/navigation/sidebar/sidebar-menu-link.tsx
src/gui/src/components/ui/shiki.tsx
src/gui/src/components/ui/tabs.tsx
src/gui/test/components/explorer-grid/selected-item/__snapshots__/tabs-manifest.tsx.snap

Closes vltpkg/statusboard#123
- **updates** `light` theme and sets background color
- **updates** hover color on tabs
- **updates** hover color on `sidebar-menu-link`

gui: bugfix manifest code viewer theme

---

infra/build/src/bundle.ts
infra/build/src/variants.ts
infra/build/tap-snapshots/test/variants.ts.test.cjs
infra/build/test/bundle.ts
scripts/bins/bundle/vlr
scripts/bins/bundle/vlr.ps1
scripts/bins/bundle/vlrx
scripts/bins/bundle/vlrx.ps1
scripts/bins/bundle/vlt
scripts/bins/bundle/vlt.ps1
scripts/bins/bundle/vlx
scripts/bins/bundle/vlx.ps1
scripts/bins/bundle/vlxl
scripts/bins/bundle/vlxl.ps1
scripts/bins/vlr
scripts/bins/vlr.ps1
scripts/bins/vlrx
scripts/bins/vlrx.ps1
scripts/bins/vlt
scripts/bins/vlt.ps1
scripts/bins/vlx
scripts/bins/vlx.ps1
scripts/bins/vlxl
scripts/bins/vlxl.ps1

build: use --no-warnings flag in bundled hashbang

---

src/cache-unzip/src/unzip.ts
src/registry-client/src/revalidate.ts
src/rollback-remove/src/remove.ts

It's ok for these to use TLA because they get called in a separate process.

await within detached scripts

---

src/gui/src/app/dashboard.tsx
src/gui/src/app/explorer.tsx
src/gui/src/app/help/help-selectors.tsx
src/gui/src/app/labels.tsx
src/gui/src/app/queries.tsx
src/gui/src/components/dashboard-grid/index.tsx
src/gui/src/components/navigation/header.tsx
src/gui/test/app/__snapshots__/dashboard.tsx.snap
src/gui/test/app/__snapshots__/explorer.tsx.snap
src/gui/test/app/__snapshots__/labels.tsx.snap
src/gui/test/app/__snapshots__/queries.tsx.snap
src/gui/test/app/help/__snapshots__/help-selectors.tsx.snap
src/gui/test/components/dashboard-grid/__snapshots__/index.tsx.snap
src/gui/test/components/navigation/__snapshots__/header.tsx.snap
src/gui/test/components/navigation/header.tsx

<p align="center">
</p>
- Updates the `header` component to contain the `context` values
- Removes the `context` value on `/` (dashboard) route due to invalid project root values
- Updates styles on components to fit with new header styles
closes vltpkg/statusboard#120

gui: header design

---

www/docs/src/content/docs/cli/registries.mdx

Based on #757 land that first
Fix: https://github.com/vltpkg/statusboard/issues/155

docs: custom registries (VLT-403)

---

src/gui/src/components/explorer-grid/selected-item/item-header.tsx
src/gui/test/components/explorer-grid/selected-item/__snapshots__/item-header.tsx.snap

Passes the correct `averageScore` value into the `progress-circle` and updates ui styles

gui: bugfix averageScore in ui

---

src/gui/src/app/explorer.tsx
src/gui/src/components/query-bar/index.tsx
src/gui/src/components/query-bar/query-highlighter.tsx
src/gui/src/components/ui/input.tsx
src/gui/src/main.css
src/gui/test/app/__snapshots__/explorer.tsx.snap
src/gui/test/components/query-bar/__snapshots__/index.tsx.snap
src/gui/test/components/query-bar/__snapshots__/query-highlighter.tsx.snap
src/gui/test/components/ui/__snapshots__/color-picker.tsx.snap
src/gui/test/components/ui/__snapshots__/input.tsx.snap

Closes vltpkg/statusboard#122
- **updates** input background color
- **bugfix:** the overflowing long selectors
- **updates:** `query-bar` implementation

gui: bugfix long selectors in query bar

---

src/gui/src/components/explorer-grid/selected-item/item-header.tsx
src/gui/src/components/explorer-grid/selected-item/tabs-insight.tsx
src/gui/src/components/explorer-grid/selected-item/tabs-versions.tsx
src/gui/test/components/explorer-grid/selected-item/__snapshots__/item-header.tsx.snap

updates data / numbers that are presented 'at-a-glance' to 'human' readable numbers.
Closes vltpkg/statusboard#174

gui: information 'at-a-glance' to human numbers

---

src/graph/src/graph.ts
src/graph/test/graph.ts

Edges should also be cleaned up during graph garbage collection.

graph: gc edges cleanup

---

src/vlx/src/install.ts
src/vlx/test/install.ts

vlx: retry without dir if vlx info fails initially

---

www/docs/src/content/docs/cli/registries.mdx

Instead of sending Ruy a bunch of messages, I decided I could get my hands dirty.

doc: JSR in special alias

---

.cursor/rules/code-validation-workflow.mdc
.cursor/rules/cursor-rules-location.mdc
.cursor/rules/linting-error-handler.mdc
.cursor/rules/monorepo-structure.mdc

Adds a main cursor rule on how to create cursor rules and start to add the first initial fundamental rules on how to work on the project.

chore: fundamental workflow cursor rules

---

src/gui/src/components/explorer-grid/overview-sidebar/index.tsx
src/gui/src/components/explorer-grid/overview-sidebar/suggested-queries.tsx
src/gui/src/components/explorer-grid/selected-item/index.tsx
src/gui/test/components/explorer-grid/__snapshots__/side-item.tsx.snap
src/gui/test/components/explorer-grid/overview-sidebar/__snapshots__/index.tsx.snap
src/gui/test/components/explorer-grid/overview-sidebar/__snapshots__/suggested-queries.tsx.snap
src/gui/test/components/explorer-grid/overview-sidebar/index.tsx
src/gui/test/components/explorer-grid/overview-sidebar/suggested-queries.tsx
src/gui/test/components/explorer-grid/selected-item/__snapshots__/index.tsx.snap
src/gui/test/components/explorer-grid/selected-item/index.tsx
src/gui/test/components/explorer-grid/side-item.tsx

This PR creates an `overview-sidebar` component, and cleans up the 'left' side of the 'selected-item' view, and adds a `suggested-queries` component to render when the user is viewing a selected item that contains dependencies.
- **refactors the `selected-item`'s left side**
- **creates `suggested-queries` component**
- **adds `suggested-queries` into `overview-sidebar/index.tsx`**
- **updates `selected-item`**

gui: suggested queries

---

src/gui/src/components/explorer-grid/results/result-item.tsx
src/gui/src/components/explorer-grid/selected-item/index.tsx
src/gui/test/components/explorer-grid/results/result-item.tsx

Fixes https://github.com/vltpkg/vltpkg/issues/871

gui: less verbose query from search results

---

README.md
scripts/check-deps.ts
src/gui/LICENSE.md
src/gui/README.md

Also adds a complete table of packages and their corresponding license in the root README file.

chore: update gui license

---

src/gui/src/components/explorer-grid/selected-item/tabs-dependencies/tabs-insights.tsx
src/gui/src/utils/human-string.ts
src/gui/test/components/explorer-grid/selected-item/tabs-dependencies/__snapshots__/tabs-insights.tsx.snap
src/gui/test/utils/human-string.ts

Added a `toHumanString` helper method to better handle variations and pluralization of strings.

gui: add pluralization in insights

---

.cursor/rules/gui-validation-workflow.mdc

The GUI has specific setup due to it being a front-end project, this rule can be a place we can use to better document how to work with this specific environment.

chore: add gui validation rule

---

.github/workflows/copilot-setup-steps.yml

Per [the docs](https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent), this PR adds a `.github/workflows/copilot-setup-steps.yml` file. This is an Actions workflow whose steps are included every time Copilot runs, to prepare the environment with the right versions, tools and scripts for it to work best. Doing this will improve Copilot's performance, reduce the number of LLM calls it needs, and improve the accuracy of it's problem solving by reducing the amount of "extra" work it needs to do.

Create `copilot-setup-steps.yml` to setup Copilot's environment

---

.cursor/rules/query-pseudo-selector-creation.mdc

Add a new cursor rule to help out when creating new query selectors.

chore: add query selector creation cursor rule

---

.cursor/rules/cli-sdk-workspace.mdc

Add a rule to improve working with the CLI workspace.

chore: add cli cursor rules

---

.cursor/rules/monorepo-structure.mdc

Add links to the recently added cursor links to the monorepo central rule.

chore: add monorepo rule links

---

.cursor/rules/linting-error-handler.mdc

Added docs on how to handle chaining array types ot avoid running into linting type errors.

chore: add type predicate example

---

src/cli-sdk/src/commands/publish.ts
src/registry-client/src/index.ts
src/registry-client/src/otplease.ts
src/registry-client/src/token-response.ts
src/registry-client/src/web-auth-challenge.ts
src/registry-client/test/otplease.ts
src/registry-client/test/token-response.ts
src/registry-client/test/web-auth-challenge.ts

cli-sdk(publish): use web auth for publish

---

src/query/src/pseudo/path.ts
src/query/test/pseudo/path.ts

Fixes `:path()` comparisons so that any leading `./` are removed before trying to compare `node.location` with the provided glob path.
Fixes: https://github.com/vltpkg/vltpkg/issues/965

query: normalize path selector comparison

---

src/security-archive/src/index.ts
src/security-archive/test/fixtures/graph.ts
src/security-archive/test/index.ts

The `@vltpkg/security-archive` should use base dep ids for its internal database and its in-memory keys so that modified packages can still rely on the same shared stored data.

security-archive: normalize dep-ids

---

src/cli-sdk/src/commands/publish.ts
src/cli-sdk/src/pack-tarball.ts

fix(publish): correct tarball attachment for scoped packages

---

src/gui/src/components/explorer-grid/index.tsx
src/gui/src/components/explorer-grid/selected-item/item-header.tsx
src/gui/test/components/explorer-grid/selected-item/__snapshots__/item-header.tsx.snap

gui: bugfix removes 'v' from item spec

---

COMMUNITY_SYNC.md

- adds a folder for meeting nodes
- adds a community sync doc with relevant information & recording release terms

chore: add community sync docs

---

www/docs/src/content/docs/cli/catalogs.mdx
www/docs/src/content/docs/cli/graph-modifiers.mdx
www/docs/src/content/docs/cli/registries.mdx
www/docs/src/content/docs/cli/selectors.mdx
www/docs/src/content/docs/cli/using-with-vsr.mdx
www/docs/src/content/docs/cli/workspaces.mdx

Add docs on how to use Graph Modifiers.

docs: add graph-modifiers entry

---

src/server/src/handle-request.ts
src/server/test/handle-request.ts

This PR creates a new endpoint in the `server` workspace, `/fs/ls` to allow interfacing with the filesystem. This endpoint will be used to list files and directories in a specified path.
This is also a pre-requisite for #1025 and vltpkg/statusboard#71, which will implement a ui to view files and directories, allowing a user to choose a default `dashboard-root` path.
```json
{
"path": "/path/to/directory"
}
```

server: create `/fs/ls` endpoint

---

src/cli-sdk/src/config/definition.ts
src/cli-sdk/src/exec-command.ts
src/cli-sdk/tap-snapshots/test/config/definition.ts.test.cjs
src/cli-sdk/tap-snapshots/test/index.ts.test.cjs
src/cli-sdk/test/commands/run.ts

cli-sdk(run, exec): add if-present flag

---

src/graph/src/diff.ts
src/graph/src/reify/index.ts
src/graph/test/diff.ts

Skip any reify operation that tries to add only optional deps.
Refs: https://github.com/vltpkg/vltpkg/issues/1088

graph: skip optional only installs

---

src/cli-sdk/src/config/index.ts
src/dep-id/src/browser.ts
src/dep-id/src/index.ts
src/dep-id/test/index.ts

Refs: https://github.com/vltpkg/vltpkg/issues/1088

dep-id: memoize parsed values

---

www/docs/src/content/docs/registry/api.mdx
www/docs/src/styles/scalar-api.css

This PR updates the styles on the vsr scalar stylesheets for sensible styles 
| Before | After |
| --- | --- |
| <img width="919" height="921" alt="Screenshot 2025-09-10 at 12 13 15" src="https://github.com/user-attachments/assets/6edd10ab-c25c-496c-b82b-2c8ab2935053" /> | <img width="930" height="915" alt="Screenshot 2025-09-10 at 12 13 02" src="https://github.com/user-attachments/assets/0c101647-6dd3-46e7-bfad-b70ac139d649" /> |

docs: updates vsr scalar styles

---

src/query/src/pseudo/malware.ts
src/query/tap-snapshots/test/pseudo/malware.ts.test.cjs
src/query/test/pseudo/malware.ts
www/docs/src/components/sidebar/data.tsx
www/docs/src/content/docs/cli/commands/query.mdx
www/docs/src/content/docs/cli/security.mdx
www/docs/src/content/docs/cli/selectors.mdx
www/docs/src/content/docs/index.mdx

- adds missing `:malware` which is a pseudo state applied when any medium or higher severity is found
- adds security documentation
Fixes: https://github.com/vltpkg/vltpkg/issues/1190

feat(query): add missing `:malware` pseudo state & docs

---

src/gui/src/components/query-builder/builder.tsx
src/gui/src/components/query-builder/item.tsx
src/gui/src/components/query-builder/options.ts
src/gui/src/components/ui/dialog.tsx
src/gui/src/lib/constants/selectors.ts
src/gui/test/components/query-builder/__snapshots__/builder.tsx.snap

|  |  |
| --- | --- |
| <img width="633" height="440" alt="Screenshot 2025-09-18 at 16 31 00" src="https://github.com/user-attachments/assets/a653de12-e70c-4f3b-b7a6-5063cf362215" /> | <img width="525" height="233" alt="Screenshot 2025-09-18 at 16 30 53" src="https://github.com/user-attachments/assets/661d24d4-181f-4f6a-b73b-30dbfb403c1d" /> |
- **bugfix: `zIndex` on dialog**
- **feat: updates `query-builder` for new `host` item**

gui: updates `host` to query builder

---

src/package-info/src/index.ts
src/package-info/test/index.ts

Add an extra layer of cache in front of the manifest retrieval function in `@vltpkg/package-info`, this speeds up cached installs by avoiding loading the very large packument files when a given resolution to a manifest request is already known.

package-info: add manifest resolution cache
